### ISSUE TITLE
[🐛 Bug]: SeleniumManagerException selenium-manager.exe is missing (Anaconda Python 3.9 selenium 4.9.0)

### ISSUE THREAD

**Issue by kwikwag** [SeleniumHQ/selenium#11980]
### What happened?

When trying to instantiate `selenium.webdriver.Chrome()` after installing selenium out-of-the-box, I get the error: `SeleniumManagerException... .../selenium-manager.exe) is missing...`. 

I am using selenium 4.9.0 installed from conda-forge on a Python 3.9 / Windows 11 environment.

I will manually install the Chrome web driver, but from what I understand the above should just work.

### How can we reproduce the issue?

```shell
Probably, install miniconda, run `conda create -n my_env -c conda-forge python=3.9 selenium` or the likes, and then run the commands:

    import selenium.webdriver
    driver = selenium.webdriver.Chrome()
```

### Relevant log output

```shell
SeleniumManagerException: Message: [c:\Users\<my_username>\Apps\miniconda3\envs\<my_env>\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe](file:///C:/Users/<my_username>/Apps/miniconda3/envs/<my_env>/lib/site-packages/selenium/webdriver/common/windows/selenium-manager.exe) is missing.  Please open an issue on https://github.com/SeleniumHQ/selenium/issues
```

### Operating System

Windows 11

### Selenium version

Python (3.9) - 4.9.0

### What are the browser(s) and version(s) where you see this issue?

Chrome 112

### What are the browser driver(s) and version(s) where you see this issue?

N/A

**Comment by diemol** [comment]
This is a duplicate of #11234, but I am not sure what the outcome is. Seems Anaconda builds it in a different way. 

@symonk @titusfortner do you know what the outcome was?

**Comment by titusfortner** [comment]
The code I referenced when I closed it does not apply to that issue. So either I linked to the wrong thing, or we didn't actually fix it.

I'm reopening that one, and we can track this there. Thanks for the report.

**Comment by KittyMurphy** [comment]
Hi, 

Apologies for commenting on this closed issue, but the related issue #11234 is locked and limited to collaborators. I'm also being affected by this bug, I tried to workaround it by downloading selenium-manager.exe from the github repo and placing it in the folder that it's supposed to be in, and now: 

`import selenium.webdriver`
 `driver = selenium.webdriver.Chrome()`

gives me the error: `Exec format error: '.../selenium/webdriver/common/linux/selenium-manager'`

**Comment by titusfortner** [comment]
Ah, I thought reopening the ticket automatically unlocked it. Fixed now. Continue conversation there. :)

**Comment by stevetracvc** [comment]
This should be fixed by #12536

**Comment by scionuait** [comment]
i have an error when i try to inizialize Chrome Driver: 

Unable to obtain driver using Selenium Manager: C:\Users\Local\anaconda3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe is missing.

i follow the discussion but i dont understend how fix it. I try to re install selenium but selenium manager is still missing...  plese can you help me?

**Comment by titusfortner** [comment]
Hmm, I can't tell what path the code would have taken to get those messages.

* what is `os.environ["CONDA_PREFIX"]` for your system?
* Can you run with logging enabled? https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/
