### ISSUE TITLE
[🐛 Bug]: Could not run selenium manager on Mac within Java

### ISSUE THREAD

**Issue by kora-rider** [SeleniumHQ/selenium#12062]
### What happened?

I tried to update my framework based on Selenium 4.0.0 up to 4.9.1 but I am not able to download any driver automatically. I always get this error:

org.openqa.selenium.manager.SeleniumManager getDriverPath
INFO: Applicable driver not found; attempting to install with Selenium Manager (Beta)
org.openqa.selenium.manager.SeleniumManager runCommand
WARNING: IOException running command [/var/folders/w5/v_wd9tx15yq470sv3l7xk1sw0000gn/T/selenium-manager203730314819166584070647341325405/selenium-manager, --browser, chrome, --output, json]: Cannot run program "/var/folders/w5/v_wd9tx15yq470sv3l7xk1sw0000gn/T/selenium-manager203730314819166584070647341325405/selenium-manager": error=86, Bad CPU type in executable
Kvě 18, 2023 2:15:30 ODP. org.openqa.selenium.remote.service.DriverFinder getPath
WARNING: Unable to obtain chromedriver using Selenium Manager: Unable to parse: 

java.lang.IllegalStateException: The path to the driver executable Unable to locate the chromedriver executable; for more information on how to install drivers, see https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/

### CPU
Apple M1 Pro

### Java
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Zulu 8.68.0.21-CA-macos-aarch64) (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Zulu 8.68.0.21-CA-macos-aarch64) (build 25.362-b09, mixed mode)

### Maven
Apache Maven 3.9.2

### How can we reproduce the issue?

```shell
WebDriver driver =  new ChromeDriver();
```

### Relevant log output

```shell
org.openqa.selenium.manager.SeleniumManager getDriverPath
INFO: Applicable driver not found; attempting to install with Selenium Manager (Beta)
org.openqa.selenium.manager.SeleniumManager runCommand
WARNING: IOException running command [/var/folders/w5/v_wd9tx15yq470sv3l7xk1sw0000gn/T/selenium-manager203730314819166584070647341325405/selenium-manager, --browser, chrome, --output, json]: Cannot run program "/var/folders/w5/v_wd9tx15yq470sv3l7xk1sw0000gn/T/selenium-manager203730314819166584070647341325405/selenium-manager": error=86, Bad CPU type in executable
Kvě 18, 2023 2:15:30 ODP. org.openqa.selenium.remote.service.DriverFinder getPath
WARNING: Unable to obtain chromedriver using Selenium Manager: Unable to parse: 

java.lang.IllegalStateException: The path to the driver executable Unable to locate the chromedriver executable; for more information on how to install drivers, see https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/
```

### Operating System

macOS Ventura 13.3.1 

### Selenium version

4.9.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 

### What are the browser driver(s) and version(s) where you see this issue?

113.0.5672.126

### Are you using Selenium Grid?

No

**Comment by kenny-q** [comment]
This is probably related with my issue, I'm using a Macbook Pro M1 as well. The difference is that I'm using WebDriverManager to manage my driver and I'm getting the old error:
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Lcom/google/common/collect/ImmutableMap;

I'm getting that error on this line ->
`driver = WebDriverManager.chromedriver().create();` //being driver an object of Webdriver from openqa.selenium.Webdriver

versions on my pom.xml:

```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
     <version>4.9.1</version>
</dependency>
<dependency>
<groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>5.3.3</version>
    <scope>test</scope>
</dependency>
```

**Comment by titusfortner** [comment]
Hmm Selenium Manager should work on M1. Can you turn on logging and set it to provide the debug output?

```
    Logger.getLogger(SeleniumManager.class.getName()).setLevel(Level.SEVERE);
    Arrays.stream(logger.getHandlers()).forEach(handler -> {
      handler.setLevel(Level.FINE);
    });
```

**Comment by kenny-q** [comment]
Ok I did a simple Java project outside of my actual project and at least the chrome driver works just fine on my Macbook Pro M1 using WebDriverManager, so my issue it's related probably to a conflict with another dependency on a Maven AEM archetype project. I'm gonna post it on Stackoverflow  to see if I can get a hand with my issue. Sorry for my noise on this post.

**Comment by titusfortner** [comment]
Note that webdriver manager is not a Selenium project. Drivers are supposed to automatically work with the latest selenium. If they don't, we want to figure out why not.

**Comment by kenny-q** [comment]
Correct, I found that the WebDriverManager is a very robust solution to integrate because I don't need to keep the driver updated that matches my actual browser version on my OS. 
So since I'm working on a AEM project, I think the issue is related with a conflict of dependencies (or a missing one) with the rest of the dependencies that are required for a AEM project. I'm actually digging into it, but not luck yet :( 

EDIT - But before going with the WebDriverManager approach, I was first using the driver downloaded on my project or then using the selenium Webdriver and I'm getting the same error in all the different options. The WebDriverManager was actually my third attempt.

**Comment by titusfortner** [comment]
So we can close this issue?

**Comment by kenny-q** [comment]
I was not the one who opened it, not sure if the original question was somehow fixed.

**Comment by titusfortner** [comment]
Ah, my mistake.

**Comment by diemol** [comment]
> Hmm Selenium Manager should work on M1. Can you turn on logging and set it to provide the debug output?
> 
> ```
>     Logger.getLogger(SeleniumManager.class.getName()).setLevel(Level.SEVERE);
>     Arrays.stream(logger.getHandlers()).forEach(handler -> {
>       handler.setLevel(Level.FINE);
>     });
> ```

@kora-rider can you please try this?

**Comment by kora-rider** [comment]
> > Hmm Selenium Manager should work on M1. Can you turn on logging and set it to provide the debug output?
> > ```
> >     Logger.getLogger(SeleniumManager.class.getName()).setLevel(Level.SEVERE);
> >     Arrays.stream(logger.getHandlers()).forEach(handler -> {
> >       handler.setLevel(Level.FINE);
> >     });
> > ```
> 
> @kora-rider can you please try this?

I tried but I get no log.

Here is the whole script: 
`import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.manager.SeleniumManager;
import org.testng.annotations.Test;

import java.io.IOException;
import java.util.Arrays;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TC_9999_Download_Driver_INT_POS {

    /**
     * Test slouží pro stažení driverů Chrome, Firefox a Edge. Pro správné stažení musíte být mimo O2 vpn.
     * Test spouštějte po aktualizaci prohlížeče.
     */
    @Test
    public void _9999_Download_Driver_INT_POS() throws IOException {

        Logger logger = Logger.getLogger(SeleniumManager.class.getName());
        logger.setLevel(Level.SEVERE);
        Arrays.stream(logger.getHandlers()).forEach(handler -> {
            handler.setLevel(Level.FINE);
        });
        Handler handler = new FileHandler("selenium.xml");
        logger.addHandler(handler);
        WebDriver driver =  new ChromeDriver();
    }
}`

Here is log:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
</log>
`

**Comment by titusfortner** [comment]
Oh, because Selenium Manager class didn't even start.

> error=86, Bad CPU type in executable
Kvě 18, 2023 2:15:30 ODP. org.openqa.selenium.remote.service.DriverFinder getPath

@bonigarcia / @p0deje have you seen this error with x64 binaries executing in aarch64 environments?

**Comment by p0deje** [comment]
@titusfortner I had no problems running x64 manager on M1, but I didn't exercise the Java package.

**Comment by bonigarcia** [comment]
@titusfortner I've never experienced this problem in a macOS M1, but I have just done a quick search about "_Bad CPU type in executable_" and yes, it seems this error can happen. To prevent this issue in the future, we may consider compiling the ARM64 version of Selenium Manager and distributing it in the bindings. Also, the bindings should detect the architecture and use the proper binary.

@kora-rider As a quick solution, installing [Rosseta 2](https://support.apple.com/en-us/HT211861) in your macOS should fix the problem. To do that, you need to open the terminal and execute the following command:

```
/usr/sbin/softwareupdate -install-rosetta -agree-to-license
```

After Rosetta 2 is successfully installed, you should be able to manage the drivers through Selenium Manager.

**Comment by titusfortner** [comment]
Yeah, I really want to minimize the number of binaries we have to package in the releases, though. 😦 
We should document Rosetta 2 as a potential solution. I'm trying to revamp (again) how we talk about this in our docs.

**Comment by kora-rider** [comment]
@bonigarcia I tried to install Rosetta 2 but still the same problem, same error :-( 

I also tried to download the Chrome driver manually and add it to the root directory and I get this error:

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'Adams-MBP-2', ip: 'fde8:b038:37ce:4655:187b:1fb:33b0:3aa7%en0'

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:561)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:229)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:101)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:84)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:52)
	at soc.oneCrm.testcases.TC_9999_Download_Driver_INT_POS._9999_Download_Driver_INT_POS(TC_9999_Download_Driver_INT_POS.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.3.1', java.version: '1.8.0_362'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:114)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	... 22 more`

When I run the same script with Selenium 4.0.0 it starts Chrome.

**Comment by bonigarcia** [comment]
That does not seem to be the same error. It is the first time you have reported the error message `Timed out waiting for driver process to start`.

I think your problem is not caused by Selenium Manager (nor WebDriverManager, if you are still using it).

A quick [search](https://stackoverflow.com/questions/52110521/org-openqa-selenium-webdriverexception-timed-out-waiting-for-driver-server-to-s) on that error message points to the version of Java. You can try to upgrade it.

And BTW, that is not an error message (`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder`) - it is a warning about using SLF4J. You can Google it for more info.

**Comment by kora-rider** [comment]
I mean when I installed Rosetta 2 I get the same error 'error=86, Bad CPU'. After that, I tried to run the script with the Chrome driver downloaded manually and I get the error: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by diemol** [comment]
@kora-rider did you follow what Boni recommended?

**Comment by kora-rider** [comment]
> @kora-rider did you follow what Boni recommended?

Sure I tried even restarting the computer after the Rosetta installation.

**Comment by sbabcoc** [comment]
@kora-rider I'm dropping into this issue without a lot of context, but I'm wondering if you're really using Java 8. A substantial percentage of Selenium 4 will run with Java 8, but a few components require Java 11. Some classes (especially those loaded via **ServiceLoader**) get instantiated behind the scenes, and the errors related to these surreptitious operations are often not surfaced in the failure stack traces. The trace you posted is from the timeout of a client request. The actual issue occurred in the server, which is a completely separate process. Another potential cause for these sorts of failures is a missing or incompatible dependency. These can take some sleuthing to figure out if you're not dying with **NoClassDefFoundError**. If you're running with mixed dependency versions, you can also see **NoSuchMethodError** failures.
As @bonigarcia stated, the message regarding **StaticLoggerBinder** is just a warning. If you want to fix this, you need to add `logback-classic` and `logback-core` to your dependencies.

**Comment by sbabcoc** [comment]
@kora-rider Another thing that might be affecting you is the absence of Service Provider Interface (SPI) declarations. In your project or its dependencies, under `META-INF/services`, there should be a file named `org.openqa.selenium.WebDriverInfo`. This file declares the fully-qualified class names for implementations of the **WebDriverInfo** interface (e.g. - `org.openqa.selenium.chrome.ChromeDriverInfo`), and the automatic driver detection seems to require these declarations to find and load the corresponding drivers. In order for ServiceLoader to load the specified provider classes, these must be available on the class path (e.g. - `selenium-chrome-driver-4.9.1.jar`). May of the browser driver JARs are dependent on `selenium-chromium-driver`, so this must be on the class path, too.

**Comment by kora-rider** [comment]
None of the above have helped.

**Comment by titusfortner** [comment]
Please run this exactly and send us the output:

```
    Logger.getLogger(SeleniumManager.class.getName()).setLevel(Level.SEVERE);
    Arrays.stream(logger.getHandlers()).forEach(handler -> {
      handler.setLevel(Level.FINE);
    });
    WebDriver driver =  new ChromeDriver();
```

**Comment by titusfortner** [comment]
Oops, i did have the logging code wrong before, please run this and send the output:

```
        Logger logger = Logger.getLogger("");
        logger.setLevel(Level.FINE);
        Arrays.stream(logger.getHandlers()).forEach(handler -> {
            handler.setLevel(Level.FINE);
        });

        WebDriver driver =  new ChromeDriver();
```

**Comment by kora-rider** [comment]
I don't know what happens, but after adding this Logger it suddenly starts working. Thank you for your help.

**Comment by titusfortner** [comment]
that... shouldn't happen lol
Does it fail again when you remove the logger?

**Comment by kora-rider** [comment]
I tried to remove the logger and delete .cache/selenium, selenium manager still working well. So I was thinking about what else may be different and I find out that I have installed WhatsApp which is running in Rosetta 2 so it might be the trigger of Rosetta in general.

So I think the command `/usr/sbin/softwareupdate -install-rosetta -agree-to-license` does not work until you run at least one app which is running under Rosetta 2.

**Comment by sawan-impacter** [comment]
Still facing issue on M2 mac OS

```
Aug 22, 2023 11:53:49 AM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Error running command: [/var/folders/6c/v55v1g9d48sf8tz5rj4_nfb80000gq/T/selenium-manager1970620710115837746476157701591620/selenium-manager, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '1.8.0_372'
Driver info: driver.version: ChromeDriver
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:148)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:450)
	at org.openqa.selenium.chrome.ChromeDriverService.createServiceWithConfig(ChromeDriverService.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:70)
```

**Comment by sawan1990** [comment]
I am facing similar issue for Mac M2 chip

````
Aug 22, 2023 11:53:49 AM org.openqa.selenium.remote.service.DriverService findExecutable
WARNING: Unable to obtain driver using Selenium Manager: Error running command: [/var/folders/6c/v55v1g9d48sf8tz5rj4_nfb80000gq/T/selenium-manager1970620710115837746476157701591620/selenium-manager, --driver, chromedriver]
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.4.1', java.version: '1.8.0_372'
Driver info: driver.version: ChromeDriver
Exception in thread "main" java.lang.IllegalStateException: The path to the driver executable The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://chromedriver.chromium.org/. The latest version can be downloaded from https://chromedriver.chromium.org/downloads
	at org.openqa.selenium.internal.Require$StateChecker.nonNull(Require.java:314)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:148)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:39)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:233)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:450)
	at org.openqa.selenium.chrome.ChromeDriverService.createServiceWithConfig(ChromeDriverService.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:70)
````

**Comment by titusfortner** [comment]
@sawan1990 that's a different issue. Try running with Selenium 4.11, we've updated quite a bit since 4.6.
