### ISSUE TITLE
[🐛 Bug]: WebSocket Path Not Working with Selenium Grid --sub-path Option

### ISSUE THREAD

**Issue by hil00137** [SeleniumHQ/selenium#13393]
### What happened?

**Description:**
After setting up Selenium Grid with the `--sub-path=/selenium-grid` option, I encountered an issue with the WebSocket path. Previously, I was able to access the WebSocket using the path `ws://ip:port/sessions/{ID}/se/vnc`. However, after adding the `--sub-path` option, the expected WebSocket path `ws://ip:port/selenium-grid/sessions/{ID}/se/vnc` does not work.

**Steps to Reproduce:**
1. Start Selenium Grid with the `--sub-path=/selenium-grid` option.
2. Attempt to access the WebSocket at `ws://ip:port/selenium-grid/sessions/{ID}/se/vnc`.

**Expected Behavior:**
The WebSocket should be accessible at the path `ws://ip:port/selenium-grid/sessions/{ID}/se/vnc`, reflecting the `--sub-path` configuration.

**Actual Behavior:**
The WebSocket path `ws://ip:port/selenium-grid/sessions/{ID}/se/vnc` is not functional, and there seems to be no alternative path that accommodates the `--sub-path` configuration.

**Additional Information:**
- This issue seems to specifically relate to the interaction between the WebSocket and the `--sub-path` option in Selenium Grid.
- Any guidance or workaround to address this issue would be greatly appreciated.

If there is no sub-path option available, could you please inform me of any other methods to set a sub-path specifically for WebSocket connections? I would greatly appreciate your guidance on this.

Thank you for your assistance in resolving this matter.

### How can we reproduce the issue?

```shell
1. Configured and launched selenium-hub in Docker with `SE_SUB_PATH=/selenium/`.
2. Set up the Selenium Grid and confirmed manager UI accessibility at `http://ip:port/selenium/#ui`.
3. Ran a JUnit Test with RemoteWebDriver and confirmed the test was executing. For ease of testing, I included a Thread.sleep(10000); statement to allow sufficient time for observation.
4. Attempted to monitor the test using VNC:
   - The VNC request from the manager interface connects to an URL without the `/selenium` prefix.
   - Direct VNC connection to `ws://ip:port/session/{ID}/se/vnc` is successful.
   - However, attempting a VNC connection to `ws://ip:port/selenium/session/{ID}/se/vnc` fails to establish a connection.
```

### Relevant log output

```shell
Not Important
```

### Operating System

WSL2 with selenium docker

### Selenium version

Java 4.16.1

### What are the browser(s) and version(s) where you see this issue?

Chrome 119

### What are the browser driver(s) and version(s) where you see this issue?

Not Important

### Are you using Selenium Grid?

4.16.1

**Comment by diemol** [comment]
Does it work if you do not use Docker?

**Comment by diemol** [comment]
@vietnd96 do you know? I believe this was fixed.

**Comment by hil00137** [comment]
@diemol 
I executed the Selenium hub using the command below and found the same issue as when running it through Docker.

`
java -jar selenium-sever-4.16.1.jar hub --sub-path /selenium/
`


**Screenshots showing the sub-path added to the manager launched via command line.**
![Screenshot 2024-01-05 at 10.34.48](https://github.com/SeleniumHQ/selenium/assets/34833461/7fd70aea-5a81-47ad-ba8a-ff935d0c9ab1)


**When requesting the WebSocket URL without /selenium/**  
![Screenshot 2024-01-05 at 10.51.20](https://github.com/SeleniumHQ/selenium/assets/34833461/53583c9e-dd1f-41b9-9b5c-b1bb645904c4)


**When requesting the WebSocket URL with /selenium/**  
<img width="1693" alt="스크린샷 2024-01-05 오전 10 55 50" src="https://github.com/SeleniumHQ/selenium/assets/34833461/063fc818-0c61-41cd-a4db-5c20c6a8252c">

**Comment by VietND96** [comment]
Looks like my fix only works when there is ingress configured upfront - as the comment and reproduce https://github.com/SeleniumHQ/selenium/issues/12791#issuecomment-1847592555
For docker standalone, or start locally via `java -jar`, the issue still present

**Comment by hil00137** [comment]
@vietnd96 
I've kept the hub running in the -jar form and configured docker-nodes with the following command: 
```bash
docker run -p 5555:5555 -e SE_EVENT_BUS_HOST=<hub-ip> \
 -e SE_EVENT_BUS_PUBLISH_PORT=4442 \ 
 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
 -e SE_VNC_NO_PASSWORD=1 \ 
 -e SE_VNC_VIEW_ONLY=1 \
 -e SE_NODE_GRID_URL=http://<hub-ip>:4444/selenium \
 -v ${PWD}/selenium-http-jdk-client.jar:/opt/selenium/selenium-http-jdk-client.jar \ 
 -v ${PWD}/config.toml:/opt/bin/config.toml \
 -v /var/run/docker.sock:/var/run/docker.sock \
 selenium/node-docker:4.16.1
```

The contents of config.toml are as follows:
```toml
[docker]
configs = [
  "selenium/standalone-chrome:120.0", '{"browserName": "chrome", "browserVersion": "120.0"}',
  ....
]

[server]
host = "<node-ip>"
port = 5555
```

In this setup, when attempting a VNC connection from the manager, it tries to connect to the URL with /selenium appended. However, the actual successful connection can only be established to the URL without /selenium.

manager request like this. but failed connect
<img width="1693" alt="스크린샷 2024-01-05 오후 6 14 19" src="https://github.com/SeleniumHQ/selenium/assets/34833461/5b3214d3-cd9e-434e-b8a6-b6d552c6538b">

I tried without /selenium, success connect
<img width="1706" alt="스크린샷 2024-01-05 오후 6 13 37" src="https://github.com/SeleniumHQ/selenium/assets/34833461/273cb666-2a78-432a-8d7c-b6b15f24ff7b">

I am currently testing to set up a Selenium Grid using Docker nodes as shown above.

**Comment by VietND96** [comment]
I suspect something around here

https://github.com/SeleniumHQ/selenium/blob/485658916ca823c0cbd3db70806967a4cb7d7bd1/java/src/org/openqa/selenium/grid/router/Router.java#L66

@joerg1985, do you have any idea on this? do we need to add Route.prefix in case subPath present in Router config?

**Comment by diemol** [comment]
Not sure it is there, maybe it is around `ProxyNodeWebsockets`.

**Comment by VietND96** [comment]
> Not sure it is there, maybe it is around `ProxyNodeWebsockets`.

@diemol, you're correct. I raise PR #13407 to fix it.

**Comment by VietND96** [comment]
Hi @hil00137, if you have time, can you do a test with my image containing the fix from namespace  `ndviet/<image>:latest` and confirm?
All configs are the same as you mentioned in the above comment

**Comment by hil00137** [comment]
@vietnd96 
It appears that when attempting a WebSocket connection, it tries to connect using a URL with `/selenium` appended.
```bash
docker run -p 5555:5555 -e SE_EVENT_BUS_HOST=<hub-ip> \
 -e SE_EVENT_BUS_PUBLISH_PORT=4442 \ 
 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
 -e SE_VNC_NO_PASSWORD=1 \ 
 -e SE_VNC_VIEW_ONLY=1 \
 -e SE_NODE_GRID_URL=http://<hub-ip>:4444/selenium \
 -v ${PWD}/selenium-http-jdk-client.jar:/opt/selenium/selenium-http-jdk-client.jar \ 
 -v ${PWD}/config.toml:/opt/bin/config.toml \
 -v /var/run/docker.sock:/var/run/docker.sock \
 ndviet/node-docker:latest
```

Configuration for config.toml:
```toml
[docker]
configs = [
  "ndviet/standalone-chrome:latest", '{"browserName": "chrome"}',
  ....
]

[server]
host = "<node-ip>"
port = 5555
```
I also ran the selenium-hub using the Docker image you mentioned.

While the WebSocket connection is successful, it seems to close immediately if the Duration is less than 10 seconds. It's not exact, but it appears that only after exceeding about 10 seconds, the connection remains properly open without closing, allowing me to view the screen.

<img width="1506" alt="스크린샷 2024-01-08 오후 6 06 13" src="https://github.com/SeleniumHQ/selenium/assets/34833461/50135f6b-c744-44cb-8a93-e5306286abfa">


<img width="1694" alt="스크린샷 2024-01-08 오후 6 05 39" src="https://github.com/SeleniumHQ/selenium/assets/34833461/5f17bd3a-5539-4242-a3e3-328471ac1427">


The two images were run at different times, so the session IDs are different, but the same issue occurs every time they are executed.

For testing purposes, I used RemoteWebDriver to execute the code and then added a long Thread.sleep in the next line for testing.

**Comment by VietND96** [comment]
@hil00137, thank you. There is an error message that I could not see in my local while testing `noVNC requires a secure context (TLS). Expect crashes!`
I saw ` -v ${PWD}/selenium-http-jdk-client.jar:/opt/selenium/selenium-http-jdk-client.jar \`. How about if unset this one?

**Comment by diemol** [comment]
@hil00137 you never mentioned you are using the `node-docker` images. It would be good if you actually share how you are running the Grid.

**Comment by hil00137** [comment]
@vietnd96  
Even when I remove the configuration for selenium-http-jdk-client.jar and try again, the WebSocket connects properly after a certain amount of time, just like in my previous attempts.

**Comment by hil00137** [comment]
@diemol  
I didn't mention it in the main text, but I thought the issue with the WebSocket trying to connect to a strange URL was independent of Docker usage. 
I am currently setting up a Selenium grid consisting of one selenium-hub and one selenium node-docker, both using Docker. Both are on the same server, but I am accessing them using an external IP, not localhost, to make it easier to separate them when expanding the grid in the future. For the node-docker, I have set it up for Chrome and Edge standalone.

```toml
[docker]
configs = [
  "selenium/standalone-chrome:120.0", '{"browserName": "chrome", "browserVersion": "120.0"}',
  "selenium/standalone-edge:120.0", '{"browserName": "MicrosoftEdge", "browserVersion": "120.0"}'
]

[server]
host = "<node-ip>"
port = 5555
```

**Comment by diemol** [comment]
Fixed by https://github.com/SeleniumHQ/selenium/pull/13407
