### ISSUE TITLE
Firefox 43 disable Firefox Web-driver

### ISSUE THREAD

**Issue by g1franc** [SeleniumHQ/selenium#1385]
Hi, its seems this issue is related to https://github.com/SeleniumHQ/selenium/issues/1382

**Comment by g1franc** [comment]
The web driver is disable as it is not signed.

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
:"6.13.0.13771","st":1450218300371,"mt":1381312682000},"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0","st":1450218306441,"mt":1450218306379}},"winreg-app-global":{"{F003DA68-8256-4b37-A6C4-350FA04494DF}":{"d":"C:\\Program Files\\Logitech\\SetPointP\\LogiSmoothFirefoxExt","e":false,"v":"6.5","st":1429803677642,"mt":1400527944000}}}
1450288334567	addons.xpi	DEBUG	Existing add-on fxdriver@googlecode.com in app-profile
1450288334569	addons.xpi	DEBUG	Existing add-on {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A} in app-global
1450288334569	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1450288334570	addons.xpi	DEBUG	Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1450288334571	addons.xpi	DEBUG	Existing add-on {F003DA68-8256-4b37-A6C4-350FA04494DF} in winreg-app-global
1450288334571	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\francogu\\AppData\\Local\\Temp\\anonymous816896705125029021webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1450288332691,"mt":1450288332665}},"app-global":{"{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}","e":false,"v":"6.13.0.13771","st":1450218300371,"mt":1381312682000},"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0","st":1450218306441,"mt":1450218306379}},"winreg-app-global":{"{F003DA68-8256-4b37-A6C4-350FA04494DF}":{"d":"C:\\Program Files\\Logitech\\SetPointP\\LogiSmoothFirefoxExt","e":false,"v":"6.5","st":1429803677642,"mt":1400527944000}}}
1450288334573	addons.xpi	DEBUG	No changes found
1450288334580	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1450288334581	addons.manager	DEBUG	Provider finished startup: XPIProvider
1450288334581	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1450288334581	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1450288334581	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1450288334582	addons.manager	DEBUG	Starting provider: GMPProvider
1450288334586	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1450288334587	addons.manager	DEBUG	Provider finished startup: GMPProvider
1450288334587	addons.manager	DEBUG	Starting provider: PluginProvider
1450288334587	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1450288334587	addons.manager	DEBUG	Provider finished startup: PluginProvider
1450288334588	addons.manager	DEBUG	Completed startup sequence
1450288334670	addons.xpi-utils	DEBUG	Starting async load of XPI database C:\Users\francogu\AppData\Local\Temp\anonymous816896705125029021webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1450288334810	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1450288334810	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1450288334810	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1450288334928	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1450288334928	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1450288334930	addons.xpi-utils	DEBUG	Successfully read XPI database
1450288335000	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1450288335000	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1450288335000	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript warning: https://self-repair.mozilla.org/en-US/repair/, line 8: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:182)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:95)
	at eu.europa.opoce.ted.AppTest.openBrowser(AppTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by g1franc** [comment]
Work around it with:

> final FirefoxProfile firefoxProfile = new FirefoxProfile();
>        firefoxProfile.setPreference("xpinstall.signatures.required", false);
>        driver = new FirefoxDriver(firefoxProfile);

**Comment by AutomatedTester** [comment]
This has been fixed in later version of FirefoxDriver. You appear to be using 2.45 and the latest is 2.48.

**Comment by antiphp** [comment]
I cant find the fix in 2.48.2 - when starting the Selenium Server JAR there is this log output:
15:44:59.801 DEBUG - Extracting /customProfileDirCUSTFFCHROME to /tmp/customProfileDir699769
If I search this folder I can't find any (text) file containing "xpinstall", especially theres nothing in prefs.js where I think Firefox expects its User Preferences. So its not fixed?!

**Comment by sksajjan** [comment]
this is working fine with selenium 2.48.2 version. please add maven dependency for the same version for selenium-firefox-driver. This will sort the issue.

**Comment by hubertgrzeskowiak** [comment]
Is the fix in 2.48.2 a signed extension or just the disabling of signature checking? Because latter will not work in FX 44 anymore.

**Comment by antiphp** [comment]
Hi,

its still using unsigned signatures, the disabling did not work for me. 
Beside that, I think I understood the whole "Selenium" case - so Im 
using WebDriver now (not Selenium Suite/RC), which works with every FF 
version perfectly.

Cheers,
antiphp

Am 11.01.2016 um 14:04 schrieb Hubert Grzeskowiak:

**Comment by hubertgrzeskowiak** [comment]
@antiphp This issue exists for both Selenium versions.

**Comment by sksajjan** [comment]
The only thing I did to resolve is just by adding following to the pom.xml and it worked fine for me. Currently I am running tests on Firefox 43.0.3 with selenium 2.48.2. And also by have a dependency for the firefox browser in the pom.xml.

<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-firefox-driver</artifactId>
			<version>2.48.2</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.48.2</version>
		</dependency>

**Comment by harriswong** [comment]
Hi,

I can confirm this is still happening with Firefox 43.0.4 and Selenium standalone server 2.49.0.

I am running Selenium standalone server 2.49.0 as a node. I got the 2.49.0 from the download page http://www.seleniumhq.org/download/. 

I am experiencing the same problem with Firefox 43.0.4 with the command:
`java -jar selenium-server-standalone-2.49.0.jar -trustAllSSLCertificates -role node -hub http://ip:4444 -port xxxx -browser browserName=firefox,maxInstances=5 -maxSession 10 -timeout 20000`

Firefox complains that the WebDriver extension is disabled because it is using 2.45.0. Does the 2.49.0 standalone server still uses 2.45.0 web driver?

**Comment by Shnitzelil** [comment]
Hey,
We've two machines with 43.0.4 version and Webdriver 2.48.2
The first machine is working and the other one not!!
Is it possible that this working only on 32bit???

Coz' we've replaced the firefox 64 bit with the 32 bit and it worked...

Anyone verify it?

**Comment by karlnicholas** [comment]
I'm getting same problem as @harriswong.

**Comment by g1franc** [comment]
Mine is not working with 64bit

**Comment by barancev** [comment]
Yes, Firefox x64 is not supported at the moment, watch the issue #1431
