### ISSUE TITLE
Select Command not works in geckodriver

### ISSUE THREAD

**Issue by fraja89** [SeleniumHQ/selenium#2668]
## Meta -
OS:  

Browser:  
<!- Firefox? 

Dropdown id = Select command was not works
Select List1 = new Select(driver.findElement(By.id("TaxMonthEndId")));
	  List1.selectByValue("July");

https://gist.github.com/anonymous/e847bc9a100c2fd361e6d787938cab83
[18:39] <Guest30161> https://gist.github.com/anonymous/74bba1626bf3ba737ff18b4b26592846

-->

Browser Version:

**Comment by Easyman123** [comment]
I experienced the same issue being unable to select from dropdown when using firefox browser and geckodriver in my automated tests.

You can try to use methods selectByIndex(int i) or selectByVisibleText(String s) instead of selectByValue(String s) but for me no one of these three options worked.

**Comment by fraja89** [comment]
Thanks for your feedback

Thanks & Regards,

 F.Raja

**Comment by lukeis** [comment]
Please log GeckoDriver issues with Mozilla.

https://github.com/mozilla/geckodriver/issues

Please be sure to include a completely reproducible test script for them, without a way to reproduce the issue you are seeing there is no good way for them to fix the problem. A reproducible test script includes a WebDriver script and a link to the page in question. If you can not provide a link, create one using jsfiddle.net

**Comment by fraja89** [comment]
The Other two command two command was not working with geckodriver.

Thanks & Regards,

 F.Raja

**Comment by AutomatedTester** [comment]
This has been fixed and will be in Firefox 49

**Comment by fraja89** [comment]
When we would expect Firefox 49..Do you have any alternate solution for
this?Since we have recorded all our code mostly using the Select
Command..It is very difficult to modify.

Thanks & Regards,

 F.Raja

**Comment by lukeis** [comment]
https://wiki.mozilla.org/RapidRelease/Calendar

Sept. 13

**Comment by Easyman123** [comment]
Two of the three select commands (selectByVisibleText and selectByValue) are fixed in firefox browser version 49.0 but selectByIndex still throws an exception and doesnt work in yesterday released new firefox version 49.0.

**Comment by fraja89** [comment]
Yes ..But now i could see more problems..Now Xpath was not working in the
Latest Version...

Thanks & Regards,

 F.Raja

**Comment by streetfighter16** [comment]
I am still getting this issue, can not select value from a dropdown.
I am using these versions-
Selenium- 3.11.0
Firefox - 60.0
Python - 3.4
GeckoDriver - 0.20.1

Can anybody help with this?

**Comment by premji456** [comment]
Site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!
