### ISSUE TITLE
3.0.x selenium SessionCleaner insideBrowserTimeout and clientGoneTimeout not working properly

### ISSUE THREAD

**Issue by mzhang444** [SeleniumHQ/selenium#2973]
## Meta -

OS:  OSX 10.12 Sierre
Selenium Version:  3.0.1 java standalone server, 3.0.0.beta2 javascript client binding
Browser:  Safari 10.0 (12602.1.50.0.10)
## Expected Behavior -

I thought insideBrowserTimeout matches browserTimeout, and clientGoneTimeout matches timeout in the hub and node configuration parameters.
1. If browserTimeout and timeout is configured in the selenium hubConfig.json file, Selenium node should pick up those values, and so are insideBrowserTimeout and clientGoneTimeout. 
2. In selenium nodeConfig.json file, I set browserTimeout: 60000, timeout: 120000, the values are in milliseconds according to documentation.  SessionCleaner should pick up these values
3. If the testing running inside browser finishes but not calling webdriver.quit(), the clientGoneTimeout should be triggered, session is destroyed and the browser instance is free to be used again 
## Actual Behavior -
1. From hub grid console, I can see the selenium node configuration has browserTimeout and timeout value set correctly from the hub configuration, but according to node.log, SessionCleaner still uses default insideBrowserTimeout (0) and clientGoneTimeout (1800000)
2. According to node.log, SessionCleaner uses insideBrowserTimeout 60000000 and clientGoneTimeout 120000000. Somehow times 1000 on the milliseconds again.
3. Session is destroyed after clientGoneTimeout expires. However, the hub doesn't seem to be notified of this event, so from the hub console, that browser instance is grey out and cannot be used.
## Steps to reproduce -
1. Start hub with following command
   `java -jar selenium-server-standalone-3.0.1.jar -role hub -log hub.log -port 4444 -host <ip> -hubConfig hubConfig.json`, and hubConfig.json:
   `{
   "browserTimeout": 60000,
   "timeout": 120000
   }`
2. Start node with following command
   `java -jar selenium-server-standalone-3.0.1.jar -role node -log node.log -hub $HUB_URL -nodeConfig nodeConfig.json`, and nodeConfig.json:
   `{
   "capabilities":
   [
       {
           "browserName":"safari",
           "maxInstances":1,
                       "platform":"MAC",
                       "version":"10",
                       "seleniumProtocol": "WebDriver"
       }
   ],
   "debug": false,
   "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
   "register": true,
   "registerCycle": 5000,
   "maxSession":6,
   "port":"7777"
   }`
3. check node.log and you will see the following lines:
   `11:40:18.427 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000`
4. add the following properties to nodeConfig.json and restart selenium node
       `"browserTimeout": 60000,
   "timeout": 120000`
5. check node.log and you will see the following lines:
   `11:45:57.387 INFO - SessionCleaner initialized with insideBrowserTimeout 60000000 and clientGoneTimeout 60000000 polling every 6000000"`
6. change browserTimeout and timeout in nodeConfig.json to the following and restart selenium node
       `"browserTimeout": 60,
   "timeout": 120"`
7. check node.log and you will see the following lines:
   `11:52:21.122 INFO - SessionCleaner initialized with insideBrowserTimeout 60000 and clientGoneTimeout 120000 polling every 6000`
8. Run a QUnit test but don't call webdriver.quit() when test finishes
9. After 120 seconds, browser is shutdown as expected due to client timeout and the following log can be seen in node.log:
   `11:56:15.237 INFO - Session 4e364367-9f6e-43fc-8591-ad27c82506c9 deleted due to client timeout`.

However, the hub doesn't seem to be aware of the session being deleted. From the hub console page, that instance remains grey out and cannot be used.

**Comment by lukeis** [comment]
you need to specify the cleanUpCycle on the hub too

**Comment by mzhang444** [comment]
The hub console shows cleanupCycle for the hub and the node is 5000, the default value. Do I need to specify it explicitly in the hubConfig and nodeConfig json?

Here is the hub configuration output from hub console web page:
updated with params :
browserTimeout : 60000
debug : false
help : false
jettyMaxThreads : -1
role : hub
timeout : 120000
cleanUpCycle : 5000
maxSession : 1
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : 30000
throwOnCapabilityNotPresent : true

**Comment by mzhang444** [comment]
@lukeis The hub console shows cleanupCycle for the hub and the node is 5000, the default value. Do I need to specify it explicitly in the hubConfig and nodeConfig json?

Here is the hub configuration output from hub console web page:
updated with params :
browserTimeout : 60000
debug : false
help : false
jettyMaxThreads : -1
role : hub
timeout : 120000
cleanUpCycle : 5000
maxSession : 1
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : 30000
throwOnCapabilityNotPresent : true

**Comment by derinbay** [comment]
@mzhang444 Found any solution to this? Same problem here. Instance remains grey out on selenium grid console and cannot be used. 
@lukeis cleanUpCycle is set by default to 5000 and I can see it on grid console config.

**Comment by Eyjafjallajokull** [comment]
I'm having the same issue using docker latest images.

**Comment by Eyjafjallajokull** [comment]
Ok, I have figured this out! I've have previously set `timout` for hub to 120000 but it seems that this value should be in seconds, not milliseconds. After changing `timeout` to 120, browser sessions were released in hub.

**Comment by derinbay** [comment]
@Eyjafjallajokull Are you sure it's not milliseconds? Is it going down after 2 minutes, or 1.2 seconss?  I'll try this one also. If that's the case documentation needs to be update.

**Comment by lukeis** [comment]
It's seconds:

https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/internal/utils/configuration/StandaloneConfiguration.java#L118-L119

**Comment by derinbay** [comment]
All right, thanks @lukeis

**Comment by derinbay** [comment]
Problem is still exist on me.
My node configuration is:

    {
      "capabilities": [
        {
          "browserName": "firefox",
          "firefox_profile": "selenium",
          "platform": "WIN10",
          "maxInstances": 12
        },
        {
          "browserName": "chrome",
          "platform": "WIN10",
          "webdriver.chrome.driver": "path\\to\\chromedriver.exe",
          "maxInstances": 12
        }
      ],
      "configuration": {
        "port": 5555,
        "hub": "http://hubaddress/grid/register",
        "maxSession": 12
      }
    }

and my hub is:
    {
      "browserTimeout": 300,
      "timeout": 600
    }

When a test has failed, it's remain as greyed out in console:
<img width="409" alt="screen shot 2016-11-05 at 15 54 20" src="https://cloud.githubusercontent.com/assets/2565698/20030149/37c112ee-a370-11e6-948f-b212f6d8aca6.png">

node configurtion seems like this on console:
<img width="727" alt="screen shot 2016-11-05 at 15 54 29" src="https://cloud.githubusercontent.com/assets/2565698/20030170/89f83baa-a370-11e6-8433-c952ee938926.png">

and hun config is seems like this on console:
<img width="816" alt="screen shot 2016-11-05 at 15 57 50" src="https://cloud.githubusercontent.com/assets/2565698/20030180/bfd7bc00-a370-11e6-8c21-a4237ab283c7.png">

**Comment by mach6** [comment]
@derinbay  
You can't use that `-nodeConfig` on a 3.0.0+ selenium node without getting this error;
```shell
Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error with the JSON of the config : Deprecated -nodeConfig file encountered. Please update the file to work with Selenium 3. See https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json for more details.
```
you sure that is your node config?

**Comment by derinbay** [comment]
@mach6 Yes, you can use -nodeConfig on selenium 3 also. Only json file is changed a bit. You can see the new file template from here: https://github.com/SeleniumHQ/selenium/blob/master/java/server/src/org/openqa/grid/common/defaults/DefaultNodeWebDriver.json

Simply remove the "configuration" tag from the file and it will be ok.

**Comment by mach6** [comment]
@derinbay yes, I know. I wrote that change ;) 

my point is the config file you mentioned above for reproducing the issue is not a Se3 compatible one

**Comment by derinbay** [comment]
@mach6 oh ok :)
Well, I don't get any exception with these configurations. Both hub and nodes are using selenium3. My only problem is browser is staying hanged when a problem occured on the test and session is deleted.

**Comment by mach6** [comment]
@derinbay back to my question.. are you sure the `-nodeConfig` you supplied is above is the one you are using? it can't be... perhaps you using one that is equal and missing the `configuration { }` block?  I'm trying to get enough details for attempt reproducing this. :)

**Comment by derinbay** [comment]
@mach6 Yes, sorry I'm using the file without the configuration. I wrote the wrong old json file above. But insides are same except the configuration. and there is 1 extra "register": true line

    {
      "capabilities": [
        {
          "browserName": "chrome",
          "platform": "WIN10",
          "webdriver.chrome.driver": "C:\\path\\to\\chromedriver.exe",
          "maxInstances": 12
        }
      ],
      "port": 5555,
      "hub": "http://hubaddress:4444/grid/register",
      "maxSession": 12,
      "register": true
      }
    }

**Comment by Eyjafjallajokull** [comment]
@derinbay this json file is not valid there is one extra "}" in the end. Remove it and try again.

**Comment by derinbay** [comment]
@Eyjafjallajokull Thanks, I'm working with valid json file. I wrote typos here because I can't copy paste at the moment. The problem is not about json file validation, It couldn't even work if there is a validation error on json file : ) It's about the same problem as @mzhang444 mentioned.

**Comment by mzhang444** [comment]
@derinbay I resolved problem number 3 by setting timeout: 120 and browserTimeout: 60 in the hub.   These two properties are in seconds, while others such as registerCycle, cleanupCycle are in milliseconds. The unit used among properties are not consistent and very confusing.

Problem number 1 still exists but if we configure the hub properly, the hub will instruct the node to do the right thing.

**Comment by mach6** [comment]
Confirmations and observations:

1. Yes, the configuration for `timeout` and `browserTimeout `should be specified in _seconds_.
2. The server code internally converts these to milliseconds and in some cases displays them as such. For Example: `SessionCleaner` `INFO` messages displays values where were internally converted using `TimeUnit.SECONDS.toMillis(value)`
3. There is a bug where the `hub` in all 3.x version (with the current version being 3.0.1) where hub values are read but NEVER used to start a new node. Furthermore, the bug exists in such a fashion where the `node` registers to the `hub` with the `hub` values -- even though it is not using them. 
4. There is a bug and/or documentation issue preventing `nodes` from registering with `timeout` and `browserTimeout` values that override the `hub` values. This document suggests that this path is supported (though not recommended) -- https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-timeouts-version-221-required.  

As a work-around / because of 3 & 4, you need to sync your `timeout` and `browserTimeout` values across the `hub` and all `nodes`, specifying them in BOTH places during startup as config parameters.

I will provide fixes for 3 & 4 soon.

**Comment by ChrisAuto** [comment]
I have set both timeout and browserTimeout for the hub and nodes to be the same and double checked this. When tests fail the grid console is showing that it is greyed out and the console always displays "Error - Unable to kill process with PID"

**Comment by ChrisAuto** [comment]
How do i get this fix, do i need to wait for the next build for selenium-server-standalone.jar ?

**Comment by mach6** [comment]
Re-opening.. Only point `3` above is fixed..

**Comment by shirandedan** [comment]
i wanna ask how you solve your problem at last..i meet the same problem as yours..

**Comment by derinbay** [comment]
@shirandedan I solved by updating selenium from 3.0.1 to newer one.

**Comment by shirandedan** [comment]
@derinbay but what i used is selenium 3.2.0 and selenium-server 3.2.0,the latest version.

**Comment by shirandedan** [comment]
@derinbay i've also tried to set up the browserTimeout and tiemout,but just it didn't work!

**Comment by shirandedan** [comment]
what should i do to solve it 
Config for the hub :
browserTimeout : 0
debug : false
help : false
port : 4444
role : hub
timeout : 1800
cleanUpCycle : 5000
host : 192.168.199.146
maxSession : 40
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true
Config for the hub :
browserTimeout : 0
debug : false
help : false
port : 4444
role : hub
timeout : 1800
cleanUpCycle : 5000
host : 192.168.199.146
maxSession : 40
capabilityMatcher : org.openqa.grid.internal.utils.DefaultCapabilityMatcher
newSessionWaitTimeout : -1
throwOnCapabilityNotPresent : true

**Comment by ChrisAuto** [comment]
This is still not fixed even with update to selenium 3.3.1.  
Upon a failed test, the node displays in console "unable to kill process with PID XXXX". 
Grid Console still shows greyed out firefox icons for every failed test. When all slots are greyed out, no more connections are allowed and the entire suite fails.

**Comment by anantpatil56** [comment]
Hi All,
I am facing the following issue in selenium(3.0.1,3.3.1 and 3.4) grid execution .

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

In node machine its showing even changed timeout to 120 and browserTimeout to 60 in both node and hub.
SessionCleaner insideBrowserTimeout and clientGoneTimeout 120000 polling every 6000

Please help me .

**Comment by diemol** [comment]
Closing this issue has gone stale and in addition Grid 2.x and 3.x are not under development anymore. If someone has this issue still, we suggest to join the community channel https://seleniumhq.herokuapp.com/ to solve the related questions, and/or try the new Grid 4 (which is in the alphas at the moment of this comment).
