### ISSUE TITLE
3.3.1 versus geckodriver 0.15 firefox 51: "Not all requiredCapabilities could be met"

### ISSUE THREAD

**Issue by starpit** [SeleniumHQ/selenium#3711]
## Meta -
OS:  Linux

Selenium Version:  3.3.1

Browser:  geckodriver 0.15

Browser Version:  firefox-51.0

   Build info: version: '3.3.1', revision: '5234b325d5', time: '2017-03-10 09:10:29 +0000'
    System info: host: 'fdbef2c9e650', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.12-moby', java.version: '1.8.0_111-internal'
    Driver info: driver.version: FirefoxDriver
## Expected Behavior -
success, with selenium 3.3.0 against the same geckodriver and firefox versions

## Actual Behavior -
after upgrading to selenium 3.3.1, failures:

 org.openqa.selenium.SessionNotCreatedException: Not all requiredCapabilities could be met: ["UEsDBBQACAgIAHt6eEoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WyW7bMBC99ysKn1qgJrK0l/aUpilQIGiKGkGPBEWOJMYUyXKx4r/vUEvs2DKV9GRLmiFnefPeRA+OWgflu0XhTItPxLMSuv9SV6RhqmUOCGhWKBCLD29Lpjy8//Im7jwFC2hjjQvJpQamQt0/EzTaSD7jryG0xq1JHYIltpa+3i7TZ8u8XyrQVajR8eLTp+duY8AOmMAfAQF4APFdOh+uMBauAN2Ci4fhmgbzeqS8dqYB6rmTNlAXNQ2ySS6XZ9MXBVZ4guXQd/paGQ/T2YzWwrRaGSbwLs2qVNjatH9q0CusVqrUtLvFoGzw6TLaGMHUTO1hE4xRnoBzxnGjvVH75T5O38tKG41Va6ApwK26R5/PxYP3Eq2CQSw48BHrVmKglDvm67yvknpNjAVN4TGA00ylZr4aQWVq6++opy9roRBObvCZcQ7Yzqgxc49woBxc8JOVeOqU9FaxLYib87PVT4PISa39OG2Mr8Sd/iM19tefnxGJF5n737fosWCFieFzoZheL44x1ydEmVL0wWMxUpyyL/1xbI9WYrnRlrS1DKCkD3jA3yjdKSQkGKxlIMM0jajD5BIWsgVQDBuDA5CHmk+4jZbUODUWz6YtKJ4mKLrU0sVByqnbukMNiRYbDERjacvtPZq8mkeiTaN0kw0PeHQybBEpCvAf8cFJHqhxspKaWqMk3+ahqqHFsSNDPpluPgu0P5mkl6tYNLIblV/dy6sOjC/jzcljshk/TefQmNQUtDzBXrs5xDTbDr/Hg2jKEu1gyaz1BNFnWlpsqYCSRRWm6WQsO/d2wM90tMd4yKJthDNiH5kquC3pmbGzv5izzR49VuTm/vaKXBK2a9Jxeg9sw3qFyJLqYSvGGcnjaBQ+zpAJNrBMUGBq+SLRPM7ZwUMngNkAe4in0PLH73WLxWC+9Syy4gigRFjn8xJ5h1CbPbtQhq87cntRxzwwx+sBP3Py25Ae5UTExma7h2h/ESafAceg2jgpppn1iIwOWehyGgk9ay/HMUQ4hTijzYPtCYoZdp35JWdPQX2n7zsFRSqKHWdnK5dgMh3E3gyZXvK6XeiHvu7XlZNb2qBdtGMtgWXUFU06MAOSGlA2eQ18/a0nrq/9l9fLGmFCyBQxm1GEyeX5f5dmZaoqvRy2uawG7M1Sl/E1ciQLspAqoU/Lqg7qhOrtuY43/g/F0XEQSIP7YQfERdopHRzUaLfSpBUUgY2L5MxOs5t7Vfpo+1Vgt238A1BLBwjbq6ZPpQMAAL4MAABQSwECFAAUAAgICAB7enhK26umT6UDAAC+DAAABwAAAAAAAAAAAAAAAAAAAAAAdXNlci5qc1BLBQYAAAAAAQABADUAAADaAwAAAAA= does not equal undefined"] (WARNING: The server did not provide any stacktrace information)

**Comment by blackwhites** [comment]
I have exactly same issue with you

**Comment by botmike** [comment]
same issue, on ubuntu,  sel 3.3.1
- strange thing is, I have it working on real ubuntu server, but not on ubuntu in VM.  wasted a lot of time trying to get this running, still stuck

**Comment by botmike** [comment]
stack exception from running webdriver

java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'username-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.8.0-36-generic', java.version: '1.8.0_121'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'username-VirtualBox', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.8.0-36-generic', java.version: '1.8.0_121'
Driver info: driver.version: unknown

**Comment by botmike** [comment]
found a solution, by calling the jar locally (also changed the names of some folders, maybe path too long, also took out quotes, not sure what issue was?)

instead of
java -Dwebdriver.gecko.driver="/home/username/workspace/third_party_drivers/geckodriver" -jar /home/username/workspace/webdriver/_standalone331/selenium-server-standalone-3.3.1.jar

I used;
java -Dwebdriver.gecko.driver=/home/username/workspace/thirdparty/geckodriver -jar selenium-server-standalone-3.3.1.jar

**Comment by LinuxSuRen** [comment]
driver = new FirefoxDriver();这样不带任何参数的情况下就可以，操作系统为win7，更详细的代码为https://github.com/LinuxSuRen/phoenix.framework/blob/master/src/main/java/org/suren/autotest/web/framework/selenium/SeleniumEngine.java

**Comment by si-mikey** [comment]
@botmike this is still not working for me

**Comment by TranQuocViet** [comment]
i'm facing the same probem :(

**Comment by si-mikey** [comment]
@TranQuocViet  if your pushing a profile for FF then try disabling that and try again. My issue was resolved when I removed the profile. I'm still trying to find a solution.

**Comment by lmtierney** [comment]
Please provide concise reproducible test cases and describe what results you are seeing and what results you expect.

**Comment by maurizio-lattuada** [comment]
Hi guys,
I'm facing the same issue with Selenium 3.3.1 (java) and geckodriver 0.15.0.
I'm using Firefox 52.0.2 on Windows 7 (64 bit) and the project is build with maven 3.3.3 and using java 1.8.0_121. It is launched with the classic "mvn -U compile test-compile test".

FYI I tried also to delete completely that Firefox profile and to recreate it from scratch (using Firefox clearly), but no success.
The only extensions installed in that profile are:
- Clear Recent History
- Firebug
- Firepath

By only rolling back to Selenium 3.3.0, now the browser is correctly launched and any web page can be open.

**Comment by vinaynalla1401** [comment]
even the above issue still existed " Not all requiredCapabilities could be met"

when i push existed firefox profile i  am facing same issue

**Comment by akshat62** [comment]
Provide code.

Use
`driver.get("http://www.google.com/");`

WebDriver only responds to http requests.

**Comment by p0deje** [comment]
Please provide [concise reproducible test case](http://sscce.org/) so that we could act on this issue.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)

**Comment by barancev** [comment]
Closing the issue due to inactivity. But I think it should be fixed by the changes made to fix #3808
