### ISSUE TITLE
IEdriver cannot switch to popup openend from a popup

### ISSUE THREAD

**Issue by PascalGit1** [SeleniumHQ/selenium#4364]
**OS:  Windows 7
Selenium Version:  3.4.0
Browser:  Internet Explorer (version 11.0.9600.18738 - 32bit)** 

When i'm inside a popup and open another popup from that window, it will not be able to "see" this popup and the driver will freeze when trying to switch to it.

When using the following code to handle the switching it works fine on both chrome and firefox driver:

```
	public void getWindow() {
		Set<String> handles = driver.getWindowHandles(); // get all window handles
		for(String test:handles){
			System.out.println(test);
		}
		Iterator<String> iterator = handles.iterator();
		parentWindowHandler = iterator.next(); // The parent window is the top window
		while (iterator.hasNext()) {
			subWindowHandler = iterator.next();
		}
	}

	@When("^switch to popup$")
	public void switch_to_popup() throws Throwable {
		getWindow();
		System.out.println("switch to popup: " + subWindowHandler);
		driver.switchTo().window(subWindowHandler);
	}

	@When("^switch to mainwindow$")
	public void switch_to_mainwindow() throws Throwable {
		getWindow();
		driver.switchTo().window(parentWindowHandler);
	}
```

**Comment by jimevans** [comment]
There is not enough information here to act on this report. Knowing how the driver was created (with what capabilities) is critical, as is having a site against which to test. A trace-level log of output from the IE driver would also be most useful.

Moreover, the provided code is not correct, as there is no guarantee of order in the handles returned by `getWindowHandles`. That is to say, the first handle in the list is not the top-most, nor the first opened during the session.

Finally, there are tests in the Selenium code base that opens multiple popup windows, and these tests run for IE without failure for me, so the driver is not globally broken in this case.

I'd be more than happy, my time willing, to look at the issue, but I can't until the above things are corrected.

**Comment by PascalGit1** [comment]
How the driver was created:
```
      System.setProperty(PROPERTY_DRIVER_INTERNET_EXPLORER, PATH_DRIVER_INTERNET_EXPLORER);
      driver = new InternetExplorerDriver();
```
Because it freezes im not sure if i can get a tracel-level log of output

The thing about the windowhandles is that it doesn't even show up the 3rd handle with the print statement which it does do for the other browsers.

I will try and get the other information aswell

**Comment by RajAsapu** [comment]
I am not sure whats the cause is , but are you using the updated version of IE web driver ! and just want to confirm that it is not edge web driver .

**Comment by PascalGit1** [comment]
Yes i am using the updated version of IE web driver.
My previous statement about it working on chrome and firefox is still true, the reason for this is that it gets the handles always in the same order with the parent always above the child.
So i have reworked the methods for IE to look like this:

```
public class PopupDefinition extends AbstractStepDefinition {
	String parentWindowHandler = driver.getWindowHandle();
	String subWindowHandler;
	String currentWindowHandler;

	public void getWindow() {
		Set<String> handles = driver.getWindowHandles(); // get all window handles
	
		Iterator<String> iterator = handles.iterator();
		while (iterator.hasNext()) {
			String getHandler = iterator.next();
			if(!getHandler.equals(parentWindowHandler)){
			subWindowHandler = getHandler;
			}
		}
	}

	
	@When("^switch to second popup$")
	public void switchToSecondPopup() throws Throwable {
		TimeUnit.SECONDS.sleep(2);
		
		Set<String> handles = driver.getWindowHandles(); // get all window handles
		currentWindowHandler = driver.getWindowHandle();
		
		Iterator<String> iterator = handles.iterator();
		while (iterator.hasNext()) {
			String getHandler = iterator.next();
			if(!getHandler.equals(parentWindowHandler)&&!getHandler.equals(currentWindowHandler)){
			subWindowHandler = getHandler;
			}
		}
		
		driver.switchTo().window(subWindowHandler);
		TimeUnit.SECONDS.sleep(2);
	}
	
	@When("^switch to popup$")
	public void switchToPopup() throws Throwable {
		TimeUnit.SECONDS.sleep(2);
		getWindow();
		driver.switchTo().window(subWindowHandler);
		TimeUnit.SECONDS.sleep(2);
	}

	@When("^switch to mainwindow$")
	public void switchToMainwindow() throws Throwable {
		driver.switchTo().window(parentWindowHandler);
	}
```

This now also works for some of the IE cases but i still have some popups that don't get picked up at all by the driver.getWindowHandles( );

**Comment by PascalGit1** [comment]
Alright i have found the cause of this, when you open a popup as a modal window the IE driver will have trouble detecting it.
 Initinally this wasn't a problem but when you open another popup from the modal window IE can never detect this 3rd window.

**Comment by royfripple** [comment]
@jimevans 

I just started encountering this issue as of Wednesday, 08/02/2017.  I don't recall when I had last run this successfully prior to that, but I believe it was some time in the last week of July.  To be clear though, this scenario was working for me.  I was building out a test that opens a modal dialog which then opened a second modal dialog.  It was correctly selecting an element on the second dialog and then clicking a button to close it.

As of now, I can still open and control one level of modal dialogs but the second level of dialogs is never registered by the driver.

In my research of this issue, I found an old issue from the selenium archive where someone was having this problem in 2013.  I downloaded the provided sample there and ran it, to make sure it wasn't an issue with my code.  [Selenium archive issue 6416](https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6416)

I'm running the same version of IE and Selenium (Java) as @PascalGit1, as well as Windows 7.

I'm attaching my log file as well as the sample code/pages that I ran from the original issue.
* __Log:__ [IEDriverLog.txt](https://github.com/SeleniumHQ/selenium/files/1201791/IEDriverLog.txt)
* __Java Test Case:__ [showmodal.zip](https://github.com/SeleniumHQ/selenium/files/1201806/showmodal.zip)

**Comment by jimevans** [comment]
Let me be clear about my earlier comment on this issue. I never said it wasn't a legitimate issue in the driver. Only that there wasn't enough information in the report to act on it. Now, it appears there may be (that depends on whether the attached test case includes pages against which to test). I make no guarantees for when I will have availability to look at it, since I don't get paid to work on the IE driver, and I have a family to support. Thank you for the additional information.

**Comment by royfripple** [comment]
Yep, completely understood on all accounts.  I responded specifically to you to try and provide more detail since there wasn't enough to go on originally and I started encountering the same problem (this being after it had originally worked for me).

The test case does include the necessary pages to run the test.  It'll just have to be updated to point to wherever you save the HTML files.

Any help you can provide is appreciated!

**Comment by royfripple** [comment]
Just a quick update.  Our organization installed patch KB4025252 for IE 11 sometime the week of July 31st.  It appears that the issue started to occur after that point in time.  I'm going to try to revert to the previous version to see if I can verify whether or not that was the problem.

**Comment by zappingseb** [comment]
I had a similar problem:

OS: Win 7 Enterprise
IE11: 11.0.9600.18738 (KB4025252)
Selenium IEDriver: 3.5 32 bit

I added the capabilities:

```
ie.forceCreateProcessApi=false,
InternetExplorerDriver.INTRODUCE_FLAKINESS_BY_IGNORING_SECURITY_DOMAIN=false
InternetExplorerDriver.IGNORE_ZOOM_SETTING=true
requireWindowFocus=true
enablePersistentHover=true
```

Adding the DWORD `TabProcGrowth ` in 
`HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main`
with value `0` solved the problem. I can access two windows now.

**Comment by royfripple** [comment]
This is working again for me after switching to the 3.5 IE driver.  Thanks for responding and pointing out the update!  I did a bit of testing with and without the registry change and for me it didn't seem to matter.  It would stop working when I switched back to the 3.4 IE driver though.

It does appear that this issue is resolved.

**Comment by diemol** [comment]
Closing after reading the previous comment.
