### ISSUE TITLE
Window is closed issue: but window is not closed.

### ISSUE THREAD

**Issue by blueray333** [SeleniumHQ/selenium#5061]
## Meta -
OS:  Windows 7

Selenium Version:  3.6

Browser:  IE 11

Browser Version:   11.0.9600.18816 64-bit

## Expected Behavior -
Username should be typed on the field. 

## Actual Behavior -
Exception in thread "main" org.openqa.selenium.NoSuchWindowException: Window is closed
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'
System info: host: 'A118653', ip: '10.34.192.178', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{acceptInsecureCerts=false, browserVersion=11, se:ieOptions={nativeEvents=true, browserAttachTimeout=0, ie.ensureCleanSession=false, elementScrollBehavior=0, enablePersistentHover=false, ie.browserCommandLineSwitches=, ie.forceCreateProcessApi=false, requireWindowFocus=true, initialBrowserUrl=http://localhost:34248/, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, ignoreProtectedModeSettings=false}, browserName=internet explorer, pageLoadStrategy=normal, javascriptEnabled=true, platformName=WINDOWS, setWindowRect=true, platform=WINDOWS}]
Session ID: a9018a6d-710e-4aaf-868e-c32a3c29e925
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:643)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:503)
	at cucumberTest.SeleniumTest.main(SeleniumTest.java:38)

## Steps to reproduce -
I'm trying this online selenium short tutorial, and I'm encountering this issue (window is closed), but the window is not closed.  Below is my code. 

	
	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub
		WebDriver driver;
		
		String IEDriverLocation = "C://jars//IEDriverServer_x64_3.6.0//IEDriverServer.exe";
		
		File file = new File(IEDriverLocation);
		System.setProperty("webdriver.ie.driver", file.getAbsolutePath());
		
		DesiredCapabilities ieCapabilities = DesiredCapabilities.internetExplorer();
		ieCapabilities.setCapability("requireWindowFocus", true);
		ieCapabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);
		InternetExplorerOptions s = new InternetExplorerOptions(ieCapabilities);
		
		driver = new InternetExplorerDriver(s);
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		driver.manage().window().maximize();
		driver.get("http://www.store.demoqa.com");
		System.out.println(driver.getWindowHandle());  //checking if there is a handle returned
		driver.findElement(By.xpath(".//*[@id='account']/a")).click();
		Thread.sleep(4000);
		System.out.println(driver.getWindowHandle()); //FAILS HERE
		driver.findElement(By.id("log")).sendKeys("testuser_1"); //FAILS ALSO HERE if the previous code line is omitted.
		
	}

**Comment by lmtierney** [comment]
Can you upgrade to IEDriverServer `3.7.0` and try again? There were some issues fixed in there that you could be hitting

**Comment by blueray333** [comment]
Thanks for the reply.  I downloaded 3.7.0 and used it. It shows more error info, but still says "no such window"..

Nov 16, 2017 6:47:42 AM org.openqa.selenium.remote.ErrorCodes toStatus
INFO: HTTP Status: '404' -> incorrect JSON status mapping for 'no such window' (400 expected)
Exception in thread "main" org.openqa.selenium.NoSuchWindowException: Window is closed
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:26.402Z'
System info: host: 'A118653', ip: '10.34.192.178', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{proxy=Proxy(), acceptInsecureCerts=false, browserVersion=11, se:ieOptions={nativeEvents=true, browserAttachTimeout=0, ie.ensureCleanSession=true, elementScrollBehavior=0, enablePersistentHover=false, ie.browserCommandLineSwitches=, ie.forceCreateProcessApi=false, requireWindowFocus=true, initialBrowserUrl=http://localhost:29530/, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, ignoreProtectedModeSettings=false}, timeouts={implicit=0, pageLoad=300000, script=30000}, browserName=internet explorer, pageLoadStrategy=normal, javascriptEnabled=true, platformName=WINDOWS, setWindowRect=true, platform=WINDOWS}]
Session ID: 36ae81dc-168f-48d8-b7af-b9e3ebcad18e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:643)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:503)
	at cucumberTest.SeleniumTest.main(SeleniumTest.java:37)

**Comment by barancev** [comment]
Upgrade the client library to version 3.7 too.

**Comment by blueray333** [comment]
I downloaded all updates, 3.7.0 IE Driver, 3.7.1 Selenium Standalone server and 3.7.1 Selenium client and web driver language bindings.  replaced the old one with this new one on the java build path.  Still have the error..

Exception in thread "main" org.openqa.selenium.NoSuchWindowException: Window is closed
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'A118653', ip: '10.34.192.178', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities {acceptInsecureCerts: false, browserName: internet explorer, browserVersion: 11, javascriptEnabled: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:ieOptions: {browserAttachTimeout: 0, elementScrollBehavior: 0, enablePersistentHover: false, ie.browserCommandLineSwitches: , ie.ensureCleanSession: true, ie.fileUploadDialogTimeout: 3000, ie.forceCreateProcessApi: false, ignoreProtectedModeSettings: false, ignoreZoomSetting: false, initialBrowserUrl: http://localhost:23828/, nativeEvents: true, requireWindowFocus: true}, setWindowRect: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: ca4de5cc-d733-4458-b859-eda7d3e4df03
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

**Comment by barancev** [comment]
For the record: the provided sample works for me in both 3.6 and 3.7.

**Comment by blueray333** [comment]
I have a more complex website that I used the same code, but changed the id's and the link, and it works. this issue only happens on this website, that's weird..

**Comment by pricelessspirit** [comment]
I am experiencing the same issue for IE11 and Windows 7 environment. I think it is something to do with windows 7 environment because the same set of tests run fine on Windows 2008 R2 and IE11.

**Comment by KS261187** [comment]
I am getting the same issue but with the IE driver 3.8.0 and Webdriver 3.8.0. Can someone please help?

**Comment by barancev** [comment]
Can you please set Protected mode = On for all security zones and check if the issue persists?

**Comment by shankarkc** [comment]
@barancev  thanks for the hint. I too had above exception and it worked fine after setting IE  ```Protected mode = On``

**Comment by diemol** [comment]
After reading the comments, it seems the issue is solved, feel free to reopen in case this is not true and please provide all the requested information from the issue template.
