### ISSUE TITLE
Merging of `*Option` classes doesn't work as it did for DesiredCapabilities

### ISSUE THREAD

**Issue by JohnA2** [SeleniumHQ/selenium#5279]
## Meta -
OS:
Windows 7
Selenium Version:
3.6.0 - 3.8.1
Browser:
Internet Explorer,  Firefox and Chrome
Browser Version:
any

## Expected Behavior -
Browser specific parameters in descendants of `MutableCapabilities` work after merging them.

## Actual Behavior -
Browser specific parameters are ignored because they are lost after using `merge`.

## Steps to reproduce -
**Short example:**
```
ChromeOptions options1 = new ChromeOptions();
ChromeOptions options2 = new ChromeOptions();
options2.addArguments("--start-maximized");
options1.merge(options2);
WebDriver driver = new ChromeDriver(options1); // Chrome doesn't start maximized
```

**Long example:**
I use a "SeleniumConfig" class to store all WebDriver related configuration, including its `Capabilities`. There are two types of the SeleniumConfig objects - the global that applies to all test classes and locals that only apply to one test class. So I need to merge global and local Capabilities when initializing a new test class.

A simplified version of my code looks like this:
```
// Class that contains all configuration for a WebDriver
class SeleniumConfig {
	private String browser = BrowserType.FIREFOX;
	// ... other parameters
	private DesiredCapabilities capabilities = new DesiredCapabilities();
	
	public SeleniumConfig() {}
	public SeleniumConfig(SeleniumConfig configToCopy) {
		this.browser = configToCopy.getBrowser();
		this.capabilities = new DesiredCapabilities(configToCopy.getCapabilities());
	}
	public String getBrowser() {
		return browser;
	}
	public void setBrowser(String browser) {
		this.browser = browser;
	}
	public DesiredCapabilities getCapabilities() {
		return capabilities;
	}
	public void addCapability(String key, Object value) {
		this.capabilities.setCapability(key, value);
	}
}

// A singleton that holds configuration for all test classes
class GlobalSettings {
	private static final GlobalSettings instance = new GlobalSettings();
	private SeleniumConfig global = new SeleniumConfig();

	private GlobalSettings() { // Read global configuration from some source
		// For example start Chrome maximized
		global.setBrowser(BrowserType.CHROME);
		ChromeOptions options = new ChromeOptions();
		options.addArguments("--start-maximized");
		global.addCapability(ChromeOptions.CAPABILITY, options);
	}
	public static SeleniumConfig getGlobalSettings() {
		return instance.global;
	}
}

// An example of a test class
public class SeleniumTest1 {
	WebDriver driver;
	private SeleniumConfig local;

	@BeforeClass
	public void setUp() {
		local = new SeleniumConfig(GlobalSettings.getGlobalSettings()); // Copy global settings
		// Customize local (unique to this test class) configuration here if needed
		if (local.getBrowser().equals(BrowserType.FIREFOX)) driver = new FirefoxDriver(local.getCapabilities());
		else if (local.getBrowser().equals(BrowserType.CHROME)) driver = new ChromeDriver(local.getCapabilities());
		else if (local.getBrowser().equals(BrowserType.IE)) driver = new InternetExplorerDriver(local.getCapabilities());
	}
	
	@AfterClass
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	public void testSomething() {
		driver.get("http://example.com");
	}
}
```

It worked fine before version 3.6.0 and still works even in the latest version, but since 3.6.0 I get "The constructor *Driver(Capabilities) is deprecated" warnings, so I tried to rewrite this code:

```
// Class that contains all configuration for a WebDriver
class SeleniumConfig {
	private String browser = BrowserType.FIREFOX;
	// ... other parameters
	private Map<String, MutableCapabilities> browserSpecificCapabilities = new HashMap<>();
	
	public SeleniumConfig() {
		browserSpecificCapabilities.put(BrowserType.FIREFOX, new FirefoxOptions());
		browserSpecificCapabilities.put(BrowserType.CHROME, new ChromeOptions());
		browserSpecificCapabilities.put(BrowserType.IE, new InternetExplorerOptions());
	}
	public SeleniumConfig(SeleniumConfig configToCopy) {
		this();
		this.browser = configToCopy.getBrowser();
		for (Entry<String, MutableCapabilities> entry : configToCopy.getCapabilitiesMap().entrySet()) {
			browserSpecificCapabilities.get(entry.getKey()).merge(entry.getValue());
		}
	}
	public String getBrowser() {
		return browser;
	}
	public void setBrowser(String browser) {
		this.browser = browser;
	}
	public Map<String, MutableCapabilities> getCapabilitiesMap() {
		return browserSpecificCapabilities;
	}
	public FirefoxOptions getFirefoxCapabilities() {
		return (FirefoxOptions)browserSpecificCapabilities.get(BrowserType.FIREFOX);
	}
	public ChromeOptions getChromeCapabilities() {
		return (ChromeOptions)browserSpecificCapabilities.get(BrowserType.CHROME);
	}
	public InternetExplorerOptions getIECapabilities() {
		return (InternetExplorerOptions)browserSpecificCapabilities.get(BrowserType.IE);
	}
}

// A singleton that holds configuration for all test classes
class GlobalSettings {
	private static final GlobalSettings instance = new GlobalSettings();
	private SeleniumConfig global = new SeleniumConfig();

	private GlobalSettings() { // Read global configuration from some source
		// For example start Chrome maximized
		global.setBrowser(BrowserType.CHROME);
		ChromeOptions options = global.getChromeCapabilities();
		options.addArguments("--start-maximized");
	}
	public static SeleniumConfig getGlobalSettings() {
		return instance.global;
	}
}

// An example of a test class
public class SeleniumTest2 {
	WebDriver driver;
	private SeleniumConfig local;

	@BeforeClass
	public void setUp() {
		local = new SeleniumConfig(GlobalSettings.getGlobalSettings()); // Copy global settings
		// Customize local (unique to this test class) configuration here if needed
		if (local.getBrowser().equals(BrowserType.FIREFOX)) driver = new FirefoxDriver(local.getFirefoxCapabilities());
		else if (local.getBrowser().equals(BrowserType.CHROME)) driver = new ChromeDriver(local.getChromeCapabilities());
		else if (local.getBrowser().equals(BrowserType.IE)) driver = new InternetExplorerDriver(local.getIECapabilities());
	}
	
	@AfterClass
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	public void testSomething() {
		driver.get("http://example.com");
	}
}
```

There are two problems with the new code:
1) The amount of code to do the same task increased as I need to handle capabilities for every browser separately. Is it by design or am I doing something wrong?
2) The browser specific configuration like "--start-maximized" no longer work due to the merge method in the `*Option` classes not working for browser specific parameters. It's not limited to Chrome options, at least Firefox and IE have the same problem.

**Comment by Firefds** [comment]
@barancev it seems that the issue (at least for Chrome) is in the asMap method - https://github.com/SeleniumHQ/selenium/blob/9d070940cb7d795dd4291672d36b61e9c940059a/java/client/src/org/openqa/selenium/chromium/ChromiumOptions.java#L217

When going over the capability fields (experimentalOptions, binary, args, extensionFiles, extensions) it skips checking the caps field we inherit from AbstractCapabilities - https://github.com/SeleniumHQ/selenium/blob/9d070940cb7d795dd4291672d36b61e9c940059a/java/client/src/org/openqa/selenium/AbstractCapabilities.java#L36

And therefore doesn't merge those capabilities into the new options.

**Comment by Firefds** [comment]
The issue is with this line
https://github.com/SeleniumHQ/selenium/blob/9d070940cb7d795dd4291672d36b61e9c940059a/java/client/src/org/openqa/selenium/chromium/ChromiumOptions.java#L243

When merging, the original CAPABILITY value is being overwritten by this line.
We need to get the original CAPABILITY values and add them to the args values after this
https://github.com/SeleniumHQ/selenium/blob/9d070940cb7d795dd4291672d36b61e9c940059a/java/client/src/org/openqa/selenium/chromium/ChromiumOptions.java#L227

**Comment by barancev** [comment]
Chrome part of the fix has been landed in commit ec9c67b2fb1ec110f51934832fec3cef8a9bf746

**Comment by JohnA2** [comment]
Thanks! Are there plans to fix other browsers? I'm mostly interested in Firefox and IE.

**Comment by barancev** [comment]
Merging FirefoxOptions fixed by commit e43cce39f148e83ea107f631f0922cefb89ac78d
I suppose that InternetExplorerOptions should work too. If there are actual issues with merging options please raise new issues with reproduction scenarios.

**Comment by JohnA2** [comment]
I tried to build Selenium on CentOS 7 using the instructions at https://github.com/SeleniumHQ/selenium/blob/trunk/README.md to test it. I used "bazel build java/..." and then "./go maven-install" to generate Maven artifacts. It completed without errors, but only *.pom *.pom.md5 and *.pom.sha1 files were generated in ~/.m2/repository/. All *.jar files are missing for some reason. I'm not familiar with the build tools that Selenium uses to try to figure out what went wrong, so I'll have to wait for the beta release to test it.

**Comment by JohnA2** [comment]
I reproduced the same issue with IE + 4.0.0-alpha-7 and created https://github.com/SeleniumHQ/selenium/issues/9143 as requested.

**Comment by JohnA2** [comment]
The code from my "short example" still doesn't work (Chrome doesn't start maximized) with 4.0.0-beta-1, so at least the Chrome issue wasn't fixed.

**Comment by barancev** [comment]
@JohnA2 `merge` method does not modify the object it is called in, it creates a new object that contains merged data.

**Comment by JohnA2** [comment]
Got it, thanks. In this case, merging for Chrome and Firefox look good.
