### ISSUE TITLE
Edge webdriver fails with error "invalid capability" on Windows 10 RS5 17763

### ISSUE THREAD

**Issue by gauravjoshi4u** [SeleniumHQ/selenium#6600]
-->

Browser Version:  

## Expected Behavior -
No error
## Actual Behavior -
Edge load fails with exception "invalid capability"

## Steps to reproduce -
download webdriver for Win 10 RS5

IWebDriver driver = new EdgeDriver("c:\test");
                driver.Url = link;
                IWait<IWebDriver> wait = new OpenQA.Selenium.Support.UI.WebDriverWait(driver, TimeSpan.FromSeconds(60.00));
                wait.Until(driver1 => ((IJavaScriptExecutor)driver).ExecuteScript("return document.readyState").Equals("complete"));

**Comment by jimevans** [comment]
The Edge driver for RS5 builds is no longer a separate download.

**Comment by gauravjoshi4u** [comment]
I have installed the Microsoft Webdriver through MS suggested way; Settings
> Apps > Apps & features > Manage optional features and installing it
standalone
however it fails when initializing a new instance of Edge driver class.

var driver = new EdgeDriver();


error:
[16:23:39.044] - Listening on http://127.0.0.1:57585/
[16:23:39.044] - Listening on http://[::1]:57585/
[16:23:39.533] - Invalid capabilities
Exception Type: System.InvalidOperationException
Exception details: The specified arguments passed to the command are
invalid.
Exception stack trace:    at
OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response
errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String
driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities
desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor
commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)

**Comment by jimevans** [comment]
The stack trace indicates you’re passing in an `EdgeOptions` object. What are you passing there?

**Comment by gauravjoshi4u** [comment]
I get the same error even if I simply initiate the instance without any
argument passed.
Another thing that alarms me is the exception coming from remote server
class while I am running local.

**Comment by jimevans** [comment]
There is no need for alarm in that regard. Given that all driver implementations use the same JSON-over-HTTP wire protocol to communicate with the remote end, no matter whether you’re running local or remote, the class hierarchy has `EdgeDriver` (and `ChromeDriver`, and `InternetExplorerDriver`, and `FirefoxDriver`, and so on) all are subclasses of `RemoteWebDriver`.

Now, as for your other comments, I’m thoroughly confused. You say that you installed the driver component as a so-called “feature on demand” (when you installed it through Settings), yet your sample code is still looking for the driver in a specific location on you hard drive (`new EdgeDriver("c:\test")`). Which is it? Please make sure that you have one _and only one_ copy of `MicrosoftWebDriver.exe` on your entire system, and it should be located in C:\Windows\System32 or similar*. Then please repost a full, complete set of Selenium code that reproduces the issue.

*A good way to do this is run the following command at a command prompt:

`dir C:\MicrosoftWebDriver.exe /s`

The `/s` is the important bit, as it says, “look in all subdirectories too.” It may take a long time to run, but it will show you all of the copies on the whole C drive.

**Comment by gauravjoshi4u** [comment]
There are two webdrivers installed in c:\windows\system32,
c:\windows\syswow64 but my project is compiled for 64-bit. So it should
refer to c:\windows\system32. And I see the same error when explicitly
passing the driver path as c:\windows\system32.
The errors were sent from the original code but issue persists with
following piece of code as well.

OS: Win10 RS5
Platform: x64
Webdriver: FOD
selenium v3.7
----------------------------------------------------------------------
var driver = new EdgeDriver();

                driver.Url = "https://www.bing.com";
                var element = driver.FindElementById("sb_form_q");
                element.SendKeys("webdriver");
                element.SendKeys(Keys.Enter);
                Console.ReadLine();
                driver.Quit();
-------------------------------------------------------------------------
07:53:14.867] - Listening on http://127.0.0.1:58395/
[07:53:14.867] - Listening on http://[::1]:58395/
[07:53:15.353] - Invalid capabilities
Exception Type: System.InvalidOperationException
Exception details: The specified arguments passed to the command are
invalid.
Exception stack trace:    at
OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response
errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String
driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities
desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor
commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Edge.EdgeDriver..ctor(EdgeOptions options)

**Comment by gauravjoshi4u** [comment]
any ideas?

**Comment by Haiming247** [comment]
Issue #6539 looks like the same. But I don't know how to apply this.options_.args.push('--jwp') using c# api

**Comment by jimevans** [comment]
@Haiming247 To force the deprecated legacy protocol for Edge in C#, do something like the following:

    EdgeDriverService service = EdgeDriverService.CreateDefaultService();
    service.UseSpecCompliantProtocol = false;
    EdgeOptions options = new EdgeOptions();
    IWebDriver driver = new EdgeDriver(service, options);

**Comment by Haiming247** [comment]
@jimevans Thanks for your reply. However I cannot find UseSpecCompliantProtocol property in EdgeDriverService if you look at the [doc](https://seleniumhq.github.io/selenium/docs/api/dotnet/index.html). But I fixed my issue by updating to the latest Selenium package.

**Comment by gauravjoshi4u** [comment]
@Haiming247 can you specify the selenium version please?

**Comment by Haiming247** [comment]
@gauravjoshi4u I used the following to be aligned with another project
Selenium.Support                    {3.13.0}
Selenium.WebDriver                  {3.13.0}
But I believe 3.14.0 should also work.

**Comment by gauravjoshi4u** [comment]
@Haiming247 i have updated the selenium version to 3.14 and the 'invalid capability' error went away.
however I am still seeing an error:
 OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:42623.

Please let me know the version of MIcrosoftWebdriver that is working for you.
