### ISSUE TITLE
Selenium server is no loading my user-extensions.js

### ISSUE THREAD

**Issue by msantamariapr** [SeleniumHQ/selenium#721]
Hello, I have an strange issue with selenium server and user-extensions.js.

It loads my user-extensions.js well if I run my test suite using from command line like this:

java -jar C:\selenium-server-standalone-2.46.0.jar -userExtensions C:\user-extensions.js -htmlSuite *firefox http://16.100.104.63:8081/ C:\Test-Suites\TS1.html C:\results.html

In this case it loads fine the user-extension.js because it runs the test good and in the results.html I see that the test uses the functions on the user-extentions.js as: gotoLabel, gotoIf, while and others functions.

But if I just run the server like this (passing the user-extensions.js file):
java -jar C:\selenium-server-standalone-2.46.0.jar -userExtensions C:\user-extensions.js

And then I pass the HTML using an HTMLClient made on java it Fails because does not find the functions that are defined in the user-extensions.js. It seems that's selenium server is not loading the user-extensions.js in that case.

Does anybody knows what can be happening here ?

this is the content of my user-extensions.js file:

/*
 (C) Copyright MetaCommunications, Inc. 2006.
     http://www.meta-comm.com
     http://engineering.meta-comm.com

Distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
*/

function map_list( list, for_func, if_func )
    {
    var mapped_list = [];
    for ( var i = 0; i < list.length; ++i )
        {
        var x = list[i];
        if( null == if_func || if_func( i, x ) ) 
            mapped_list.push( for_func( i, x ) );
        }
    return mapped_list;
    }

    
// Modified to initialize GoTo labels/cycles list
HtmlRunnerTestLoop.prototype.old_initialize = HtmlRunnerTestLoop.prototype.initialize

HtmlRunnerTestLoop.prototype.initialize = function(htmlTestCase, metrics, seleniumCommandFactory)
    {
    this.gotoLabels  = {};
    this.whileLabels = { ends: {}, whiles: {} };
    
    this.old_initialize(htmlTestCase, metrics, seleniumCommandFactory);
    
    this.initialiseLabels();
    }

HtmlRunnerTestLoop.prototype.initialiseLabels = function()
    {
    var command_rows = map_list( this.htmlTestCase.getCommandRows() 
                               , function(i, x) { 
                                    return x.getCommand()
                                    }
                               );

    var cycles = [];
    for( var i = 0; i < command_rows.length; ++i )
        {
        switch( command_rows[i].command.toLowerCase() )
            {
            case "label":
                this.gotoLabels[ command_rows[i].target ] = i;
                break;
            case "while":
            case "endwhile":
                cycles.push( [command_rows[i].command.toLowerCase(), i] )
                break;
            }
        }        
        
    var i = 0;
    while( cycles.length )
        {
        if( i >= cycles.length )
            throw new Error( "non-matching while/endWhile found" );
            
        switch( cycles[i][0] )
            {
            case "while":
                if(    ( i+1 < cycles.length ) 
                    && ( "endwhile" == cycles[i+1][0] )
                    )
                    {
                    // pair found
                    this.whileLabels.ends[ cycles[i+1][1] ] = cycles[i][1]
                    this.whileLabels.whiles[ cycles[i][1] ] = cycles[i+1][1]
                    
                    cycles.splice( i, 2 );
                    i = 0;
                    }
                else
                    ++i;
                break;
            case "endwhile":
                ++i;
                break;
            }
        }
                    
    }    

HtmlRunnerTestLoop.prototype.continueFromRow = function( row_num ) 
    {
    if(    row_num == undefined
        || row_num == null
        || row_num < 0
        )
        throw new Error( "Invalid row_num specified." );
        
    this.htmlTestCase.nextCommandRowIndex = row_num;
    }
    

// do nothing. simple label
Selenium.prototype.doLabel      = function(){};

Selenium.prototype.doGotolabel  = function( label ) {

    if( undefined == htmlTestRunner.currentTest.gotoLabels[label] ) 
        throw new Error( "Specified label '" + label + "' is not found." );
    
    htmlTestRunner.currentTest.continueFromRow( htmlTestRunner.currentTest.gotoLabels[ label ] );
    };
    
Selenium.prototype.doGoto = Selenium.prototype.doGotolabel;

Selenium.prototype.doGotoIf = function( condition, label ) {
    if( eval(condition) ) 
        this.doGotolabel( label );
    }

    
Selenium.prototype.doWhile = function( condition ) {
    if( !eval(condition) )
        {
        var last_row = htmlTestRunner.currentTest.htmlTestCase.nextCommandRowIndex - 1
        var end_while_row = htmlTestRunner.currentTest.whileLabels.whiles[ last_row ]
        if( undefined == end_while_row ) 
            throw new Error( "Corresponding 'endWhile' is not found." );
        
        htmlTestRunner.currentTest.continueFromRow( end_while_row + 1 );
        }
    }

Selenium.prototype.doEndWhile = function() {
    var last_row = htmlTestRunner.currentTest.htmlTestCase.nextCommandRowIndex - 1
    var while_row = htmlTestRunner.currentTest.whileLabels.ends[ last_row ]
    if( undefined == while_row ) 
        throw new Error( "Corresponding 'While' is not found." );
    
    htmlTestRunner.currentTest.continueFromRow( while_row );
    }

**Comment by msantamariapr** [comment]
I saw that someone else have the same issue that I have and on this url said that has been fixed on the next release. I tried but don't works. https://code.google.com/p/selenium/issues/detail?id=5675

Anyone have any idea of how to make Selenium Server to loads user-extensions.js and be useable by the Java Web Driver or Selenium RC Java Driver ?

**Comment by lukeis** [comment]
user-extensions is only applicable to Selenium RC (which has been deprecated and no longer supported). We'd gladly accept pull requests that "fix" any issue you encounter with Selenium RC (while it still exists). But we are not actively working on it and you are highly encouraged to convert your scripts to use WebDriver only.

**Comment by msantamariapr** [comment]
yes, there is where we are trying to use user extensions. on Selenium RC Java code. also we tried processCommand.setExtensionJs("user-extension.js") method but does not work. It returns ERROR: Unknown command gotoIf .
