### ISSUE TITLE
Using the "withTagName" method produces a "Locator must be serializable to JSON using a 'toJson' method." error

### ISSUE THREAD

**Issue by xiao1272209235** [SeleniumHQ/selenium#8368]
## 🐛 Bug Report

When I intend to use the "withTagName" method to locate elements, an error such as "Locator must be serializable to JSON using a 'toJson' method." occurs.

## To Reproduce

Use the code provided below.

## Expected behavior

1. open chrome
2. locate the element whose id is su, and input "java".
3. locate the input to the left of the element with an id of su, and click.

## Test script or set of commands reproducing this issue

```java
package com.example.selenium;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.openqa.selenium.support.locators.RelativeLocator.withTagName;

public class SeleniumDemo {

    WebDriver driver;

    @Before
    public void before() {
        System.setProperty("webdriver.chrome.driver", "C:/Users/JIAHE/OpenSource/webdriver/chromedriver.exe");
        driver = new ChromeDriver();
    }

    @Test
    public void open() {
        driver.get("https://www.baidu.com");
        WebElement kw = driver.findElement(By.id("kw"));
        kw.sendKeys("java");
        // get an error here，from withTagName
        WebElement su = driver.findElement(withTagName("input").toRightOf(kw));
        su.click();
    }

    @After
    public void after() {
        driver.quit();
    }

}

```

## Environment

OS: Windows 10
Browser: Chrome
Browser version: 83.0.4103.61
Browser Driver version: ChromeDriver 83.0.4103.39
Language Bindings version: Java1.8, webdriver is selenium-server-4.0.0-alpha-62
Selenium Grid version (if applicable):

**Comment by BVisagie** [comment]
Out of interest, I was wondering due to state changes on the DOM after your send keys to `kw` have you tried re evaluating `kw` when attempting the `toRightOf` method call? 

Example:

```
WebElement kw = driver.findElement(By.id("kw"));
kw.sendKeys("java");
WebElement su = driver.findElement(withTagName("input").toRightOf(By.id("kw")));
```

**Comment by xiao1272209235** [comment]
@BVisagie 
I don't know how to show you the changed DOM, but you can try the case at "cn.bing.com".

```java
driver.get("https://cn.bing.com");
WebElement kw = driver.findElement(By.id("sb_form_q"));
kw.sendKeys("java");
WebElement su = driver.findElement(withTagName("div").toRightOf(kw));
su.click();
```

**Comment by BVisagie** [comment]
@xiao1272209235 try: `.toRightOf(By.id("kw")));`

**Comment by BVisagie** [comment]
> @xiao1272209235 try: `.toRightOf(By.id("kw")));`

Sorry @xiao1272209235 I was not paying attention, I sent the wrong value, meant to say use: `.toRightOf(By.id("sb_form_q")));`

**Comment by seanpoulter** [comment]
If it helps, the test cases should document the intended usage. They are found in [java/client/test/org/openqa/selenium/support/locators/RelativeLocatorTest.java](https://github.com/SeleniumHQ/selenium/blob/6e8cb5b9bb20dbc8b25ea6ec818677b97385c35a/java/client/test/org/openqa/selenium/support/locators/RelativeLocatorTest.java#L33). Those two tests are failing in the TravisCI build.

I've also found the similar JavaScript tests fail and have opened #8375 to ask for some guidance for how to fix it.

**Comment by bongosway** [comment]
#8424 fixed this issue.

**Comment by barancev** [comment]
Fixed by commit e86a183b4c6121a867f9a88d713ed67bde763930

**Comment by seanpoulter** [comment]
Hey @barancev, we may want to keep this issue open or re-open #8375. We closed #8375 as a duplicate of this issue but we haven't fixed the problems with the JavaScript language bindings it described. The build still fails: https://travis-ci.com/github/SeleniumHQ/selenium/jobs/350017522#L313

Let me know if you've got any questions. I can jump on IRC.

**Comment by barancev** [comment]
Oh, sorry, I'll split the issues back.

**Comment by seanpoulter** [comment]
Thanks @barancev.
