### ISSUE TITLE
Hub reporting no available nodes after a few hours

### ISSUE THREAD

**Issue by sabelosimelane** [SeleniumHQ/selenium#9594]
## 🐛 Bug Report

I have a docker grid version 4 deployed on a docker swarm, consisting of one hub and 5 chrome nodes. The grid starts correctly and even runs tests as expected but after a few hours the hub reports that there are no available nodes. When I run a status check on the hub, it reports that it is not ready, however when I run a status check on the nodes ("_/readyz_" and "_/status_"), they report to be healthy and ready.

If I restart the hub, when it comes back up, it still cannot recognize the nodes. But, if I scale the nodes to zero and back up to 5, suddenly they are recognized by the hub and all is well again.

By the way, there are no errors on the hub and node logs.

## To Reproduce

This is my docker-compose file below and I deploy the grid using "docker stack deploy -c docker-compose.yml myapp"

## Expected behavior

The hub should not lose the nodes, unless if the nodes' status reports that they are not healthy.

## Test script reproducing this issue (when applicable)

```
version: '3.9'

services:
  chrome:
    image: selenium/node-chrome:4.0.0
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=myapp_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      - SE_NODE_SESSION_TIMEOUT=60
    ports:
      - "5555:5555"
    networks:
      - myapp-net
    links:
      - hub
    deploy:
      replicas: 5
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  hub:
    image: selenium/hub:4.0.0
    networks:
      - myapp-net
    environment:
      - SE_OPTS="--log-level FINE"
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

## Environment

OS: Centos 7
Docker-Selenium image version: selenium/hub:4.0.0

-->
Docker version: 20.10.5
Docker-Compose version (if applicable): 1.26.2, build eefe0d31
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well): docker stack deploy -c docker-compose.yml myapp

**Comment by sabelosimelane** [comment]
The issue you're describing is exactly as per our experience.

Have you tried the workaround scripts?

**Comment by sabelosimelane** [comment]
Hi @zzvara, the script will only restart the nodes if and only if there are no more nodes available for the hub to use. It can't be broken anymore than it is broken at that point.

Also, the script does not restart the hub, but instead, restarts the nodes. This means that while there are no nodes available to use, the hub will queue incoming jobs until the nodes are up and available.

Lastly, you can play around with the timing of the scripts to suit your SLA and business processes. i.e. you don't have to poll every 2 minutes, you could reduce that. You could also reduce the wait time between restarts.

**Comment by zzvara** [comment]
@sabelosimelane I think Pod Reaper is better for me, since as I observed, for a couple of hours the number of Chrome nodes will be around 5-10/40, which is very bad for my SLA. SLA dictates 30-35 nodes to be available at all times.

Hopefully, Pod Reaper will solve this by restarting "old" nodes before they get "zombie" as follows:
- any node running for more than 3 hours are subject to restart,
- in every 5 minutes, after 3 hours, the node has a 10% chance to get restarted (this helps so that nodes get unsynchronized and not all get downed at the same time after 3 hours).

These are my current numbers:
![image](https://user-images.githubusercontent.com/8371789/121591281-96fc5d00-ca39-11eb-9a9a-8bff733168e8.png)


In addition, your script would not work on Kubernetes, since nodes would have to be restarted using the K8S API interface, not Docker.

Nevertheless, your script gave me the idea to look for Pod Reaper in the first place.

**Comment by pujagani** [comment]
Thank you for providing the details. I was able to reproduce the issue over a few days. After eliminating any contention/deadlock related issues regarding this issue, I suspect the issue is due to the heap. Every once in 5-6 hours or sometimes a little over an hour, the Node stops sending the heartbeat for around 20 mins or so then resumes sending the heartbeat. This is not necessarily a consistent pattern, but it is the pattern I have observed the most in last 3 days of triaging the issue. 

**Observations**
**Note**: The logs are added only to triage the issue. Please ignore the typo.

Node Logs: 
![Screen Shot 2021-06-17 at 4 19 40 PM](https://user-images.githubusercontent.com/10705590/122566692-76e62280-d065-11eb-831f-9c089659a99f.png)


Node Heap Graph:
<img width="540" alt="Screen Shot 2021-06-17 at 4 19 30 PM" src="https://user-images.githubusercontent.com/10705590/122567060-e3f9b800-d065-11eb-869e-a2b82f97a71a.png">


Hub Logs: 
![Screen Shot 2021-06-17 at 4 20 18 PM](https://user-images.githubusercontent.com/10705590/122566896-b4e34680-d065-11eb-81c7-e4f8a130c16b.png)

Hub Heap Graph: 

<img width="551" alt="Screen Shot 2021-06-17 at 4 20 08 PM" src="https://user-images.githubusercontent.com/10705590/122567307-27ecbd00-d066-11eb-8f10-87b0652660d5.png">

The duration when Node stops sending the heartbeat is the same duration that heap graph has the visible flat line. 
That exact duration is also when the heap graph of the Hub is a flat line. 
In both cases, when the next trough occurs, the Node resumes the heartbeat and Hub is able to detect it and add it back.

**Note**: The adding the Node back logic was added as a temporary workaround to triage.

**Comment by shs96c** [comment]
One thing to bear in mind is that the heartbeat is sent via a `Regularly` from the `LocalNode`, which is single-threaded. If something blocks that thread, then the heartbeat won't be sent.

**Comment by diemol** [comment]
We've made some improvements related to this issue during the last couple of weeks, could you please check again using the most recent pre-release?
https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713

**Comment by basiljose1** [comment]
> We've made some improvements related to this issue during the last couple of weeks, could you please check again using the most recent pre-release?
> https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713

Awesome looks these bugs are fixed. in the last 24 hours there is no such issues

**Comment by Wadyasafslsa** [comment]
> ## 🐛 تقرير الشوائب
> لديّ نسخة شبكة عامل إرساء 4 منتشرة على سرب عامل ميناء ، يتألف من محور واحد و 5 عقد كروم. تبدأ الشبكة بشكل صحيح وتقوم بتشغيل الاختبارات كما هو متوقع ولكن بعد بضع ساعات ، يبلغ المحور أنه لا توجد عقد متاحة. عندما أقوم بتشغيل فحص الحالة على الموزع ، فإنه يبلغ أنه ليس جاهزًا ، ولكن عندما أقوم بتشغيل فحص الحالة على العقد (" _/ readyz_ " و " _/ status_ ") ، فإنهم _يفيدون_ بأنهم يتمتعون بصحة جيدة وجاهز.
> 
> إذا أعدت تشغيل المحور ، فعندما يعود مرة أخرى ، لا يزال يتعذر عليه التعرف على العقد. ولكن ، إذا قمت بتوسيع العقد إلى الصفر والنسخ الاحتياطي إلى 5 ، فجأة يتم التعرف عليها من قبل المحور وكل شيء على ما يرام مرة أخرى.
> 
> بالمناسبة ، لا توجد أخطاء في سجلات المحور والعقدة.
> 
> ## لإعادة إنتاج
> هذا هو ملف Docker-compose الخاص بي أدناه وأنا أنشر الشبكة باستخدام "Docker stack publish -c docker-compose.yml myapp"
> 
> ## سلوك متوقع
> يجب ألا يفقد الموزع العقد ، إلا إذا أبلغت حالة العقد أنها ليست سليمة.
> 
> ## اختبار البرنامج النصي لإعادة إظهار هذه المشكلة (عند الاقتضاء)
> ```
> version: '3.9'
> 
> services:
>   chrome:
>     image: selenium/node-chrome:4.0.0
>     volumes:
>       - /dev/shm:/dev/shm
>     environment:
>       - SE_EVENT_BUS_HOST=myapp_hub
>       - SE_EVENT_BUS_PUBLISH_PORT=4442
>       - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
>       - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
>       - SE_NODE_SESSION_TIMEOUT=60
>     ports:
>       - "5555:5555"
>     networks:
>       - myapp-net
>     links:
>       - hub
>     deploy:
>       replicas: 5
>     entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
> 
>   hub:
>     image: selenium/hub:4.0.0
>     networks:
>       - myapp-net
>     environment:
>       - SE_OPTS="--log-level FINE"
>     ports:
>       - "4442:4442"
>       - "4443:4443"
>       - "4444:4444"
> ```
> 
> ## بيئة
> نظام التشغيل:
> إصدار صورة Centos 7 Docker-Selenium: السيلينيوم / المحور: 4.0.0
> 
> ->
> إصدار Docker: 20.10.5 إصدار
> Docker- Compose (إن أمكن): 1.26.2 ، إنشاء أمر eefe0d31
> Exact Docker لبدء الحاويات (في حالة استخدام docker -compose ، قم بتوفير ملف docker-compose
> أيضًا): docker stack نشر -c docker-compose.yml myapp

**Comment by pujagani** [comment]
This issue is a tricky one to fix. I spent significant time identifying the root cause and heavily profiling the application in depth. In the process, even after fixing any potential codebase-related issue, the problem persists. 
However, based on my observations, this problem seems to happen only on MacOS and Linux-based operating systems. As mentioned in https://github.com/SeleniumHQ/selenium/issues/9594#issuecomment-864039115 , the heap-graph pattern remains the same. 
Grid in Standalone mode runs on Windows 10 machine for 5 days without any change in Node availability or request timeouts. 
When Standalone Grid runs on MacOS or docker on MacOS, the Node availability changes from UP to DOWN randomly and eventually the Node is purged. 
Upon profiling, the heap trend during random timeouts (https://github.com/SeleniumHQ/selenium/issues/9528#issuecomment-879323585) and Node heartbeat pausing is the same. Another observation is that often request timeouts happen when the Node availability is changed. This is the point of time, the system is unresponsive for a small period of time randomly. Sometimes it is reproducible after running the Grid for 20 mins, other times it could be 2 hours or 6 hours or more.

**Comment by zzvara** [comment]
This is still an issue on our end. After a few hours, Hub reported 0 Chrome nodes. [1]

[1] https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210713

**Comment by diemol** [comment]
Thank you all for the detailed feedback!

After our most recent [prerelease](https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.0.0-rc-1-prerelease-20210823), we have not been able to reproduce this anymore.

Please give it a try and if the issue is still happening, comment here with the full logs of each component and we'd be happy to reopen and check again.

**Comment by zzvara** [comment]
@diemol Thanks, we are testing it right now. Killing a Chrome Node Pod in Kubernetes in previous versions reduced node count from 60 to 59 in a few minutes, even though the Chrome Node Pod got redeployed immediately after killing. However, with the new version, killing a Chrome Node Pod increases node count to 61 in about 5 seconds after killing the pod. I suspect that it would go back to 60. It seems to be working at first glance, but I will report back any issues when encountered.

Thanks for your wonderful work!
